import json, os

U1 = "Ünite 1 – Birey ve Toplum"
U2 = "Ünite 2 – Kültür ve Miras"
U3 = "Ünite 3 – İnsanlar, Yerler ve Çevreler"
U4 = "Ünite 4 – Bilim, Teknoloji ve Toplum"
U5 = "Ünite 5 – Üretim, Dağıtım ve Tüketim"
U6 = "Ünite 6 – Etkin Vatandaşlık"
U7 = "Ünite 7 – Küresel Bağlantılar"

questions = [
    # Ek - Ünite 1 (15 soru)
    {"unite": U1, "konu": "İletişim ve Olumlu İletişim Unsurları", "yil": 2024, "zorluk": "Orta",
     "soru": "Bir ailedeki iletişim;\nI. Baba: 'Neden hep geç kalıyorsun?' (sen dili)\nII. Anne: 'Geç kalınca endişeleniyorum' (ben dili)\n\nHangisi olumlu iletişime örnektir?",
     "siklar": {"A": "I", "B": "II", "C": "İkisi de", "D": "Hiçbiri"},
     "dogru_cevap": "B", "aciklama": "Ben dili duyguyu ifade eder ve suçlamaz; olumlu iletişimdir."},
    {"unite": U1, "konu": "Medyanın Hayatımızdaki Yeri", "yil": 2024, "zorluk": "Zor",
     "soru": "Bir kişi;\nI. Farklı haber sitelerini karşılaştırmış\nII. Haberdeki iddiayı birincil kaynaktan doğrulamış\nIII. En çok paylaşılan haberi otomatik doğru kabul etmiş\n\nMedya okuryazarlığına uygun davranışlar hangileridir?",
     "siklar": {"A": "Yalnız III", "B": "I ve II", "C": "I ve III", "D": "I, II ve III"},
     "dogru_cevap": "B", "aciklama": "Karşılaştırma ve birincil kaynak doğrulama okuryazarlık; çok paylaşıma güven değildir."},
    {"unite": U1, "konu": "Kitle İletişim Özgürlüğü", "yil": 2024, "zorluk": "Orta",
     "soru": "Gazetecilerin haberleri özgürce yapabilmesi hangi hakkın korunmasına bağlıdır?",
     "siklar": {"A": "Mülkiyet hakkı", "B": "Basın özgürlüğü", "C": "Seyahat özgürlüğü", "D": "Çalışma hakkı"},
     "dogru_cevap": "B", "aciklama": "Gazetecilerin özgürce haber yapabilmesi basın özgürlüğüne bağlıdır."},
    {"unite": U1, "konu": "İletişim ve Olumlu İletişim Unsurları", "yil": 2023, "zorluk": "Zor",
     "soru": "Çatışma çözümünde;\nI. Karşıdakini dinlemek\nII. Ortak çözüm aramak\nIII. Bağırmak ve suçlamak\nIV. Uzlaşmaya çalışmak\n\nDoğru yaklaşımlar hangileridir?",
     "siklar": {"A": "I ve III", "B": "I, II ve IV", "C": "Yalnız III", "D": "I, II, III ve IV"},
     "dogru_cevap": "B", "aciklama": "Dinleme, çözüm arama ve uzlaşma doğru; bağırmak ve suçlamak yanlış yaklaşımdır."},
    {"unite": U1, "konu": "Medyanın Hayatımızdaki Yeri", "yil": 2022, "zorluk": "Orta",
     "soru": "Clickbait (tıklama tuzağı) başlıkları;\n- Abartılı ve yanıltıcı ifadeler içerir\n- Asıl haberin içeriğiyle uyuşmayabilir\n\nBu başlıklara karşı doğru tutum hangisidir?",
     "siklar": {"A": "Hemen tıklamak", "B": "Başlığa değil haberin kaynağına ve içeriğine bakmak", "C": "Başlığı okuyup yorum yapmak", "D": "En ilgi çekici başlığa güvenmek"},
     "dogru_cevap": "B", "aciklama": "Clickbait'e karşı kaynağa ve içeriğe bakmak doğru yaklaşımdır."},
    {"unite": U1, "konu": "Kitle İletişim Özgürlüğü", "yil": 2023, "zorluk": "Zor",
     "soru": "İfade özgürlüğünün sınırı;\nI. Nefret söylemi\nII. Kişilik haklarına saldırı\nIII. Kamu düzenini bozmak\n\nBu durumlardan hangileri ifade özgürlüğünün sınırını oluşturur?",
     "siklar": {"A": "Yalnız I", "B": "I ve II", "C": "I ve III", "D": "I, II ve III"},
     "dogru_cevap": "D", "aciklama": "Nefret söylemi, kişilik saldırısı ve kamu düzeni bozma ifade özgürlüğünün sınırlarıdır."},
    {"unite": U1, "konu": "İletişim ve Olumlu İletişim Unsurları", "yil": 2021, "zorluk": "Orta",
     "soru": "Aktif dinleme;\n- Göz teması kurmak\n- Başı sallamak\n- Söylenenleri özetleyerek kontrol etmek\n\nAktif dinlemenin amacı hangisidir?",
     "siklar": {"A": "Konuşmacıyı yormak", "B": "Karşıdakini gerçekten anlayarak sağlıklı iletişim kurmak", "C": "Kendi düşüncesini dayatmak", "D": "Konuyu değiştirmek"},
     "dogru_cevap": "B", "aciklama": "Aktif dinleme karşıdakini anlamayı ve sağlıklı iletişimi amaçlar."},
    {"unite": U1, "konu": "Medyanın Hayatımızdaki Yeri", "yil": 2024, "zorluk": "Orta",
     "soru": "Deepfake teknolojisi ile;\n- Gerçek olmayan video ve ses kayıtları üretilebilir\n- Kişiler söylemedikleri sözleri söylüyor gibi gösterilebilir\n\nBu teknolojinin en büyük riski hangisidir?",
     "siklar": {"A": "Eğlence sektörünü geliştirmesi", "B": "Doğru bilgiye olan güveni sarsmasi ve manipülasyona yol açması", "C": "Film endüstrisini güçlendirmesi", "D": "İletişimi hızlandırması"},
     "dogru_cevap": "B", "aciklama": "Deepfake doğru bilgiye güveni sarsarak manipülasyona yol açabilir."},
    # Ek - Ünite 2 (15 soru)
    {"unite": U2, "konu": "Beylikten Cihan Devletine", "yil": 2024, "zorluk": "Orta",
     "soru": "Osmanlı'nın genişlemesinde tımar sistemi, yeniçeri ordnusu ve hoşgörü politikası etkili olmuştur.\n\nBu faktörlerin ortak sonucu hangisidir?",
     "siklar": {"A": "Devletin zayıflaması", "B": "Güçlü ve kalıcı bir devlet yapısının oluşması", "C": "Askeri gücün azalması", "D": "Dış ticaretin durması"},
     "dogru_cevap": "B", "aciklama": "Tımar, yeniçeri ve hoşgörü güçlü ve kalıcı devlet yapısının temelini oluşturmuştur."},
    {"unite": U2, "konu": "Avrupa'da Uyanış", "yil": 2023, "zorluk": "Orta",
     "soru": "Coğrafi Keşifler sonucunda;\n- Pusula ve gemicilik gelişmiş\n- Yeni kıtalar keşfedilmiş\n- Dünya haritası değişmiş\n\nBu gelişmelerin en önemli etkisi hangisidir?",
     "siklar": {"A": "Denizciğin sona ermesi", "B": "Dünya'nın küçülmesi ve kültürler arası etkileşimin artması", "C": "Avrupa'nın yalnızlaşması", "D": "Ticaretin durması"},
     "dogru_cevap": "B", "aciklama": "Coğrafi Keşifler dünyayı küçültmüş ve kültürler arası etkileşimi artırmıştır."},
    {"unite": U2, "konu": "İnsanı Yaşat ki Devlet Yaşasın", "yil": 2023, "zorluk": "Zor",
     "soru": "Osmanlı millet sistemi;\n- Her dini topluluk kendi din, dil ve eğitim işlerini yönetmiştir\n- Kendi mahkemelerinde yargılanmıştır\n\nBu sistem hangisine örnektir?",
     "siklar": {"A": "Asimilasyon politikasına", "B": "Çoğulcu ve hoşgörüye dayalı yönetim anlayışına", "C": "Ayrımcılık politikasına", "D": "Tek tipleştirme çabasına"},
     "dogru_cevap": "B", "aciklama": "Millet sistemi farklılıklara saygı gösteren çoğulcu ve hoşgörülü bir yönetim anlayışıdır."},
    {"unite": U2, "konu": "Değişen Dünya'da Değişen Osmanlı", "yil": 2024, "zorluk": "Zor",
     "soru": "Islahat Fermanı (1856);\nI. İlahat Fermanı din farkı gözetilmeksizin eşitlik ilan etmiştir\nII. Gay-ri Müslim hakları genişletilmiştir\nIII. Avrupa devletlerinin baskısıyla hazırlanmıştır\n\nIslahat Fermanı'nın önemi hangisidir?",
     "siklar": {"A": "Sadece Müslümanların haklarını genişletmesi", "B": "Din farkı gözetmeksizin tüm vatandaşlara eşitlik tanıması", "C": "Askeri gücü artırması", "D": "Osmanlı'nın toprak kazanması"},
     "dogru_cevap": "B", "aciklama": "Islahat Fermanı tüm vatandaşlara din farkı gözetmeksizin eşitlik tanımıştır."},
    {"unite": U2, "konu": "Osmanlı'dan Kalan Mirasımız", "yil": 2024, "zorluk": "Orta",
     "soru": "Mimar Sinan;\n- Süleymaniye Camii\n- Selimiye Camii\n- Şehzade Camii gibi eserler yapmıştır.\n\nMimar Sinan'ın Türk mimarisindeki yeri hangisidir?",
     "siklar": {"A": "Sadece cami yapan bir usta", "B": "Osmanlı mimarisini evrensel düzeye taşıyan dahi mimar", "C": "Avrupa mimarisinden etkilenmiş biri", "D": "Sadece İstanbul'da çalışmış bir mühendis"},
     "dogru_cevap": "B", "aciklama": "Mimar Sinan eserleriyle Osmanlı mimarisini evrensel düzeye taşıyan dahi bir mimardır."},
    {"unite": U2, "konu": "Değişen Dünya'da Değişen Osmanlı", "yil": 2023, "zorluk": "Orta",
     "soru": "Lale Devri (1718-1730) Osmanlı'da;\n- İlk matbaa kurulmuş\n- Çiçek aşısı uygulanmış\n- Avrupa'ya elçiler gönderilmiş\n\nBu dönem hangi kavramla ilişkilidir?",
     "siklar": {"A": "Fetih dönemi", "B": "Batılılaşma ve yenileşme", "C": "Duraklama dönemi", "D": "Kuruluş dönemi"},
     "dogru_cevap": "B", "aciklama": "Lale Devri Osmanlı'da Batılılaşma ve yenileşmenin ilk adımlarının atıldığı dönemdir."},
    {"unite": U2, "konu": "Beylikten Cihan Devletine", "yil": 2022, "zorluk": "Zor",
     "soru": "Osmanlı'da padişahlar;\nI. Osman Bey → Kuruluş\nII. Fatih Sultan Mehmet → İstanbul'un Fethi\nIII. Kanuni Sultan Süleyman → En geniş sınırlar\n\nBu padişahların katkıları Osmanlı'nın hangi özelliğini gösterir?",
     "siklar": {"A": "Hep aynı güçte kaldığını", "B": "Kuruluştan yükselmeye sürekli gelişen bir devlet olduğunu", "C": "Sadece padişahların önemli olduğunu", "D": "Askeri güçten başka özelliği olmadığını"},
     "dogru_cevap": "B", "aciklama": "Kuruluştan en geniş sınırlara sürekli gelişen bir devlet yapısı söz konusudur."},
    # Ek - Ünite 3 (15 soru)
    {"unite": U3, "konu": "Nüfus ve Yerleşme", "yil": 2024, "zorluk": "Zor",
     "soru": "Türkiye'de;\nI. Doğu → Batı göçü (iş-eğitim)\nII. Kırsal → Kentsel göç (sanayileşme)\nIII. Beyin göçü (nitelikli iş gücü kaybı)\n\nBu göç türlerinin ortak sonucu hangisidir?",
     "siklar": {"A": "Nüfusun dengeli dağılması", "B": "Nüfus dağılımında dengesizlik ve bölgeler arası gelişmişlik farkı", "C": "Kırsal alanların güçlenmesi", "D": "Göçün tamamen durması"},
     "dogru_cevap": "B", "aciklama": "Göç nüfus dengesizliği ve bölgeler arası gelişmişlik farkına yol açar."},
    {"unite": U3, "konu": "İklim ve İnsan", "yil": 2024, "zorluk": "Orta",
     "soru": "Türkiye'de dört farklı iklim tipi görülür;\n- Akdeniz, Karadeniz, Karasal, Marmara (geçiş iklimi)\n\nBu çeşitliliğin temel nedeni hangisidir?",
     "siklar": {"A": "Nüfus dağılımı", "B": "Coğrafi konumu, yeryüzü şekilleri ve denize yakınlığı", "C": "Sanayi tesisleri", "D": "Eğitim düzeyi"},
     "dogru_cevap": "B", "aciklama": "Türkiye'deki iklim çeşitliliği coğrafi konum, yeryüzü şekilleri ve denize yakınlıktan kaynaklanır."},
    {"unite": U3, "konu": "Nüfus ve Yerleşme", "yil": 2023, "zorluk": "Orta",
     "soru": "Kentleşmenin olumlu ve olumsuz yönleri;\nI. İş ve eğitim imkânlarının artması → Olumlu\nII. Trafik ve gürültü sorunları → Olumsuz\nIII. Sağlık hizmetlerine erişim → Olumlu\n\nBu eşleştirmelerden hangileri doğrudur?",
     "siklar": {"A": "Yalnız I", "B": "I ve III", "C": "I, II ve III", "D": "Yalnız II"},
     "dogru_cevap": "C", "aciklama": "Kentleşme hem olumlu (iş, eğitim, sağlık) hem olumsuz (trafik, gürültü) etkilere sahiptir."},
    {"unite": U3, "konu": "İklim ve İnsan", "yil": 2023, "zorluk": "Zor",
     "soru": "Sera etkisi;\n- CO2, metan ve diğer gazlar atmosferde ısıyı tutar\n- Doğal sera etkisi dünyayı yaşanılır kılar\n- İnsan faaliyetleri sera gazlarını aşırı artırmıştır\n\nArtırılmış sera etkisinin sonucu hangisidir?",
     "siklar": {"A": "Dünyanın soğuması", "B": "Küresel ısınma ve iklim değişikliği", "C": "Sera gazlarının azalması", "D": "Ozon tabakasının kalınlaşması"},
     "dogru_cevap": "B", "aciklama": "İnsan faaliyetlerinin artırdığı sera etkisi küresel ısınma ve iklim değişikliğine yol açar."},
    {"unite": U3, "konu": "Nüfus ve Yerleşme", "yil": 2024, "zorluk": "Orta",
     "soru": "Türkiye'de nüfus sayımı elektronik ortamda ADNKS (Adrese Dayalı Nüfus Kayıt Sistemi) ile yapılmaktadır.\n\nADNKS'nin avantajı hangisidir?",
     "siklar": {"A": "Nüfus sayımını zorlaştırması", "B": "Anlık ve doğru nüfus bilgisine ulaşılmasını sağlaması", "C": "Sadece büyük şehirlerde uygulanması", "D": "10 yılda bir yapılması"},
     "dogru_cevap": "B", "aciklama": "ADNKS anlık ve doğru nüfus bilgisine ulaşılmasını sağlayan modern bir sistemdir."},
    {"unite": U3, "konu": "İklim ve İnsan", "yil": 2022, "zorluk": "Orta",
     "soru": "Paris İklim Anlaşması'nın temel hedefi hangisidir?",
     "siklar": {"A": "Sanayi üretimini durdurmak", "B": "Küresel sıcaklık artışını 1.5-2°C ile sınırlandırmak", "C": "Ülkeleri cezalandırmak", "D": "Fosil yakıt kullanımını artırmak"},
     "dogru_cevap": "B", "aciklama": "Paris Anlaşması küresel sıcaklık artışını 1.5-2°C ile sınırlandırmayı hedefler."},
    {"unite": U3, "konu": "Nüfus ve Yerleşme", "yil": 2021, "zorluk": "Zor",
     "soru": "Türkiye'de nüfusun dağılımını etkileyen faktörler;\nI. İklim ve yeryüzü şekilleri\nII. Sanayi ve iş olanakları\nIII. Ulaşım ve eğitim imkânları\nIV. Tarımsal verimlilik\n\nHangileri doğrudur?",
     "siklar": {"A": "Yalnız I", "B": "I ve II", "C": "I, II ve III", "D": "I, II, III ve IV"},
     "dogru_cevap": "D", "aciklama": "Nüfus dağılımı iklim, sanayi, ulaşım-eğitim ve tarımsal verimlilik gibi çok faktörlüdür."},
    # Ek - Ünite 4 (10 soru)
    {"unite": U4, "konu": "Avrupa'daki Bilimsel ve Teknolojik Değişimler", "yil": 2024, "zorluk": "Orta",
     "soru": "Sanayi Devrimi ilk olarak İngiltere'de başlamıştır.\n\nBunun temel nedeni hangisidir?",
     "siklar": {"A": "İngiltere'nin en büyük ülke olması", "B": "Zengin kömür yatakları, güçlü ticari filo ve serbest piyasa ekonomisi", "C": "İngiltere'nin savaşı kazanması", "D": "Diğer ülkelerin teknoloji bırakması"},
     "dogru_cevap": "B", "aciklama": "Kömür yatakları, ticari filo ve serbest piyasa İngiltere'de Sanayi Devrimi'nin başlamasını sağlamıştır."},
    {"unite": U4, "konu": "Osmanlı'da Bilim ve Teknoloji", "yil": 2023, "zorluk": "Zor",
     "soru": "Osmanlı'da yeniçerilerin reform çabalarına direnmesi;\nI. Modernleşmeyi geciktirmiştir\nII. Vaka-i Hayriye ile Yeniçeri Ocağı kaldırılmıştır\nIII. Yeni ordunun kurulmasını zorunlu kılmıştır\n\nBu süreç hangisini gösterir?",
     "siklar": {"A": "Yeniçerilerin güçlü olduğunu", "B": "Köklü kurumların değişime direnişinin reform sürecini zorlaştırdığını", "C": "Reformların gereksiz olduğunu", "D": "Osmanlı'nın değişim istemediğini"},
     "dogru_cevap": "B", "aciklama": "Köklü kurumların direnci reform sürecini zorlaştıran önemli bir faktördür."},
    {"unite": U4, "konu": "Avrupa'daki Bilimsel ve Teknolojik Değişimler", "yil": 2022, "zorluk": "Orta",
     "soru": "Newton'un yerçekimi yasası, Galileo'nun teleskop gözlemleri, Kopernik'in güneş merkezli evren modeli Bilim Devrimi'nin temelleridir.\n\nBilim Devrimi'nin en önemli sonucu hangisidir?",
     "siklar": {"A": "Dini inançların güçlenmesi", "B": "Deney ve gözleme dayalı bilimsel yöntemin yaygınlaşması", "C": "Bilimin durması", "D": "Filozofların çalışmayı bırakması"},
     "dogru_cevap": "B", "aciklama": "Bilim Devrimi deney ve gözleme dayalı bilimsel yöntemi yaygınlaştırmıştır."},
    {"unite": U4, "konu": "Osmanlı'da Bilim ve Teknoloji", "yil": 2024, "zorluk": "Orta",
     "soru": "II. Mahmut döneminde;\n- Yeniçeri Ocağı kaldırılmış\n- Posta ve karantina teşkilatı kurulmuş\n- Kıyafet değişikliği yapılmış\n- Nüfus sayımı yapılmış\n\nBu reformların ortak amacı hangisidir?",
     "siklar": {"A": "Gelenekleri korumak", "B": "Osmanlı'yı çağdaş devlet yapısına kavuşturmak", "C": "Savaşa hazırlanmak", "D": "Vergi gelirini artırmak"},
     "dogru_cevap": "B", "aciklama": "II. Mahmut reformları Osmanlı'yı modern devlet yapısına kavuşturmayı hedeflemiştir."},
    # Ek - Ünite 5 (10 soru)
    {"unite": U5, "konu": "Toprak ve İklimin Üretime Etkisi", "yil": 2024, "zorluk": "Zor",
     "soru": "Türkiye'de tarımın sorunları;\nI. Çiftçi nüfusunun yaşlanması\nII. Tarım arazilerinin kentleşmeyle azalması\nIII. Su kıtlığı ve kuraklık\nIV. Teknoloji kullanımının yetersizliği\n\nBu sorunların çözümü için en kapsamlı yaklaşım hangisidir?",
     "siklar": {"A": "Tarımı tamamen bırakmak", "B": "Genç çiftçi teşviki, sulama yatırımları ve teknoloji kullanımını artırmak", "C": "Daha fazla ithalat yapmak", "D": "Sadece organik tarıma geçmek"},
     "dogru_cevap": "B", "aciklama": "Genç çiftçi, sulama ve teknoloji birlikte uygulandığında tarım sorunlarına kapsamlı çözüm sağlar."},
    {"unite": U5, "konu": "Vakıfların Toplumsal Rolü", "yil": 2024, "zorluk": "Orta",
     "soru": "Günümüzde vakıflar;\nI. Eğitim bursları veriyor\nII. Sağlık hizmeti sunuyor\nIII. Kültürel etkinlikler düzenliyor\n\nBu faaliyetler Osmanlı vakıf sisteminden ne farkı vardır?",
     "siklar": {"A": "Temelden farklıdır", "B": "Amaç aynı (toplum yararı), yöntemler modernleşmiştir", "C": "Günümüz vakıfları kâr amacı güder", "D": "Osmanlı vakıfları daha az hizmet vermiştir"},
     "dogru_cevap": "B", "aciklama": "Hem Osmanlı hem modern vakıflar toplum yararına çalışır; yöntemler çağa uygun gelişmiştir."},
    {"unite": U5, "konu": "Toprak ve İklimin Üretime Etkisi", "yil": 2023, "zorluk": "Orta",
     "soru": "Hayvancılık;\n- Doğu Anadolu'da büyükbaş\n- Güneydoğu'da küçükbaş\n- Karadeniz'de arıcılık\n\nBu farklılaşmanın temel nedeni hangisidir?",
     "siklar": {"A": "Nüfus farkı", "B": "İklim ve coğrafi koşulların farklılığı", "C": "Devlet politikaları", "D": "Geleneksel alışkanlıklar"},
     "dogru_cevap": "B", "aciklama": "Hayvan türü dağılımı iklim ve coğrafi koşulların farklılığından kaynaklanır."},
    # Ek - Ünite 6 (10 soru)
    {"unite": U6, "konu": "Toplumsal Katılım", "yil": 2024, "zorluk": "Orta",
     "soru": "Bir vatandaş oturduğu mahallede park yapılması için imza toplamıştır.\n\nBu davranış hangisine örnektir?",
     "siklar": {"A": "Bireysel çıkar", "B": "Demokratik katılım ve toplumsal sorumluluk", "C": "Yasadışı eylem", "D": "Bürokrasi"},
     "dogru_cevap": "B", "aciklama": "İmza toplayarak talep iletmek demokratik katılım ve toplumsal sorumluluktur."},
    {"unite": U6, "konu": "Haklar, Özgürlükler ve Sorumluluklar", "yil": 2024, "zorluk": "Zor",
     "soru": "Meşrutiyet döneşminde Meclis-i Mebusan açılmış ancak padişah tarafından kapatılmıştır.\n\nBu durum hangisini gösterir?",
     "siklar": {"A": "Meclisin gereksiz olduğunu", "B": "Yasama organının yürütme tarafından engellenmesinin demokratik gelişmeyi sekteye uğrattığını", "C": "Padişahın doğru yaptığını", "D": "Halkın meclisi istemediğini"},
     "dogru_cevap": "B", "aciklama": "Meclisin kapatılması yasama organının engellenmesinin demokratik gelişmeye zarar verdiğini gösterir."},
    {"unite": U6, "konu": "Toplumsal Katılım", "yil": 2022, "zorluk": "Orta",
     "soru": "Gönüllülük;\n- Karşılık beklemeden toplum yararına çalışmak\n- Sivil toplum kuruluşlarında aktif rol almak\n\nGönüllülüğün topluma katkısı hangisidir?",
     "siklar": {"A": "Ekonomik kazanç sağlaması", "B": "Toplumsal sorunlara sivil çözüm üreterek demokrasiyi güçlendirmesi", "C": "Devletin sorumluluğunu üstlenmesi", "D": "Bireysel çıkar sağlaması"},
     "dogru_cevap": "B", "aciklama": "Gönüllülük sivil çözüm üreterek demokrasiyi güçlendirir."},
    {"unite": U6, "konu": "Haklar, Özgürlükler ve Sorumluluklar", "yil": 2023, "zorluk": "Orta",
     "soru": "Ombudsman (Kamu Denetçisi) vatandaşların devlet kurumlarıyla yaşadığı sorunlara aracılık eder.\n\nOmbudsmanın amacı hangisidir?",
     "siklar": {"A": "Devlet memurlarını cezalandırmak", "B": "Vatandaş haklarını koruyarak devlet-vatandaş ilişkisini iyileştirmek", "C": "Yeni yasalar çıkarmak", "D": "Seçimleri yönetmek"},
     "dogru_cevap": "B", "aciklama": "Ombudsman vatandaş haklarını koruyarak devlet-vatandaş ilişkisini iyileştirir."},
    # Ek - Ünite 7 (10 soru)
    {"unite": U7, "konu": "Uluslararası Örgütler ve Kuruluşlar", "yil": 2024, "zorluk": "Orta",
     "soru": "WHO (Dünya Sağlık Örgütü);\n- Küresel sağlık standartları belirler\n- Salgın hastalıklarla mücadele koordine eder\n- Aşı kampanyaları düzenler\n\nWHO'nun temel amacı hangisidir?",
     "siklar": {"A": "İlaç satışı yapmak", "B": "Dünya genelinde sağlık düzeyini yükseltmek", "C": "Sadece gelişmiş ülkelere hizmet vermek", "D": "Hastane inşa etmek"},
     "dogru_cevap": "B", "aciklama": "WHO dünya genelinde sağlık düzeyini yükseltmeyi amaçlayan uluslararası kuruluştur."},
    {"unite": U7, "konu": "Küresel Sorunlar ve Çözümleri", "yil": 2024, "zorluk": "Zor",
     "soru": "Adil ticaret (fair trade);\n- Üreticilere adil fiyat garantisi verir\n- Çocuk işçiliğini yasaklar\n- Çevre dostu üretimi destekler\n\nAdil ticaretin amacı hangisidir?",
     "siklar": {"A": "Üreticilerin daha az kazanması", "B": "Küresel ticarette adaleti ve sürdürülebilirliği sağlamak", "C": "Sadece tüketicilerin çıkarını korumak", "D": "İthalatı artırmak"},
     "dogru_cevap": "B", "aciklama": "Adil ticaret küresel ticarette adaleti ve sürdürülebilirliği sağlamayı hedefler."},
    {"unite": U7, "konu": "Uluslararası Örgütler ve Kuruluşlar", "yil": 2023, "zorluk": "Orta",
     "soru": "Avrupa Birliği (AB);\nI. Ortak pazar oluşturmuştur\nII. Üye ülkeler arasında serbest dolaşım sağlamıştır\nIII. Euro para birimini kullanmaktadır (çoğu üye)\n\nAB'nin temel amacı hangisidir?",
     "siklar": {"A": "Askeri ittifak kurmak", "B": "Ekonomik ve siyasi bütünleşme sağlamak", "C": "Sadece Avrupa kültürünü korumak", "D": "Diğer kıtaları dışlamak"},
     "dogru_cevap": "B", "aciklama": "AB ekonomik ve siyasi bütünleşmeyi sağlamayı amaçlayan bir birliktir."},
    {"unite": U7, "konu": "Küresel Sorunlar ve Çözümleri", "yil": 2022, "zorluk": "Orta",
     "soru": "Dünyada su kıtlığı;\n- 2 milyardan fazla insan temiz suya erişemiyor\n- İklim değişikliği su kaynaklarını azaltıyor\n\nSu kıtlığına karşı en etkili çözüm hangisidir?",
     "siklar": {"A": "Daha fazla baraj yapmak", "B": "Su tasarrufu, geri dönüşüm ve sürdürülebilir su yönetimi", "C": "Deniz suyunu kullanmak", "D": "Suyu sadece tarımda kullanmak"},
     "dogru_cevap": "B", "aciklama": "Su tasarrufu, geri dönüşüm ve sürdürülebilir yönetim su kıtlığına karşı en etkili çözümdür."},
    {"unite": U7, "konu": "Uluslararası Örgütler ve Kuruluşlar", "yil": 2022, "zorluk": "Zor",
     "soru": "Uluslararası Adalet Divanı (UAD);\n- BM'nin yargı organıdır\n- Devletler arası uyuşmazlıkları çözer\n- Lahey'de bulunur\n\nUAD'nin önemi hangisidir?",
     "siklar": {"A": "Bireysel davaları çözmesi", "B": "Devletler arası sorunların barışçıl yollarla çözülmesini sağlaması", "C": "Suçluları cezalandırması", "D": "Yeni yasalar çıkarması"},
     "dogru_cevap": "B", "aciklama": "UAD devletler arası sorunların barışçıl ve hukuki yollarla çözülmesini sağlar."},
    {"unite": U7, "konu": "Küresel Sorunlar ve Çözümleri", "yil": 2024, "zorluk": "Orta",
     "soru": "Siber güvenlik küresel bir sorundur;\n- Devlet sistemleri hacklenebilir\n- Kişisel verileri çalınabilir\n- Enerji altyapıları hedef olabilir\n\nSiber güvenliğin önemi hangisidir?",
     "siklar": {"A": "Sadece bilgisayar mühendislerini ilgilendirmesi", "B": "Ulusal güvenlik ve bireysel gizliliğin korunması için kritik olması", "C": "Sadece askeri alanda geçerli olması", "D": "İnternetin kapatılmasını gerektirmesi"},
     "dogru_cevap": "B", "aciklama": "Siber güvenlik ulusal güvenlik ve bireysel gizlilik için kritik bir konudur."},
]

out = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))), "data", "parts", "sorular_7_c.json")
with open(out, "w", encoding="utf-8") as f:
    json.dump(questions, f, ensure_ascii=False, indent=2)
print(f"7. Sınıf Batch C (Ek sorular): {len(questions)} soru yazıldı")
