import json, os

U1 = "Ünite 1 – Birlikte Yaşamak"
U2 = "Ünite 2 – Evimiz Dünya"
U3 = "Ünite 3 – Ortak Mirasımız"
U4 = "Ünite 4 – Yaşayan Demokrasimiz"
U5 = "Ünite 5 – Hayatımızdaki Ekonomi"
U6 = "Ünite 6 – Teknoloji ve Sosyal Bilimler"

questions = [
    {"unite": U1, "konu": "Toplumsal Birliktelik", "yil": 2024, "zorluk": "Zor",
     "soru": "Bir toplumda;\nI. Ortak dil, tarih ve kültüre sahip olmak\nII. Birlikte bayram kutlamak\nIII. Farklı görüşteki insanları dışlamak\n\nToplumsal birlikteliği güçlendiren unsurlar hangileridir?",
     "siklar": {"A": "I ve II", "B": "II ve III", "C": "Yalnız I", "D": "I, II ve III"},
     "dogru_cevap": "A", "aciklama": "Ortak değerler ve birlikte kutlama birlikteliği güçlendirir. Dışlama zarar verir."},
    {"unite": U1, "konu": "Gruplar ve Roller", "yil": 2024, "zorluk": "Orta",
     "soru": "Bir hastanede doktor tedavi eder, hemşire bakım yapar, laborant test yapar, temizlik görevlisi hijyeni sağlar.\n\nBu iş bölümü hangisinin önemini gösterir?",
     "siklar": {"A": "Sadece doktorun önemli olduğunu", "B": "Her mesleğin birbirini tamamladığını ve iş birliğinin önemini", "C": "Herkesin aynı işi yapabileceğini", "D": "Temizlik görevlisinin gereksiz olduğunu"},
     "dogru_cevap": "B", "aciklama": "Hastanede her meslek birbirini tamamlar; iş birliği hayati önem taşır."},
    {"unite": U1, "konu": "Toplumsal Sorunlar ve Çözümler", "yil": 2024, "zorluk": "Orta",
     "soru": "Bir okulda su israfını fark eden öğrenciler;\n- Musluklara tasarruf aparatı taktırmış\n- 'Su Hayattır' afişleri hazırlamış\n- Okul genelinde farkındalık kampanyası düzenlemiş\n\nBu uygulama hangisine örnektir?",
     "siklar": {"A": "Bireysel hareket", "B": "Etkin vatandaşlık ve toplumsal sorumluluk", "C": "Devlet müdahalesi", "D": "Zorunlu kural"},
     "dogru_cevap": "B", "aciklama": "Sorunu fark edip çözüm üretmek etkin vatandaşlık ve toplumsal sorumluluktur."},
    {"unite": U2, "konu": "Doğal ve Beşeri Özellikler", "yil": 2024, "zorluk": "Zor",
     "soru": "Bir bölgede;\n- Toprak verimli, yağış bol → tarım gelişmiş\n- Deniz kıyısı → balıkçılık ve turizm yaygın\n- Maden yatakları zengin → madencilik ön planda\n\nBu bilgiler hangisini destekler?",
     "siklar": {"A": "İnsan faaliyetlerinin doğal koşullardan bağımsız olduğunu", "B": "Doğal koşulların ekonomik faaliyetleri yönlendirdiğini", "C": "Her bölgede aynı faaliyetlerin yapıldığını", "D": "Teknolojinin doğal koşulları tamamen ortadan kaldırdığını"},
     "dogru_cevap": "B", "aciklama": "Toprak, iklim ve deniz gibi doğal koşullar ekonomik faaliyetleri yönlendirir."},
    {"unite": U2, "konu": "Katman ve Oluşumları Koruma", "yil": 2024, "zorluk": "Orta",
     "soru": "Karbon ayak izi, bir bireyin ürettiği sera gazı miktarıdır.\n\nKarbon ayak izini azaltmak için hangisi yanlıştır?",
     "siklar": {"A": "Toplu taşıma kullanmak", "B": "Enerji tasarruflu cihaz tercih etmek", "C": "Her yere özel araçla gitmek", "D": "Yenilenebilir enerji kullanmak"},
     "dogru_cevap": "C", "aciklama": "Özel araç kullanımı karbon ayak izini artırır, azaltmaz."},
    {"unite": U2, "konu": "Türk Dünyasıyla Kültürel İşbirlikleri", "yil": 2024, "zorluk": "Zor",
     "soru": "Türk dünyasındaki ortak kültürel ögeler;\nI. Nevruz bayramı\nII. Türk mutfak kültürü\nIII. Ortak müzik gelenekleri\nIV. Epik destanlar (Oğuz Kağan, Manas)\n\nBunların Türk devletleri arasındaki rolü hangisidir?",
     "siklar": {"A": "Siyasi birlik oluşturmak", "B": "Ortak kültürel kimliği ve kardeşlik bağlarını güçlendirmek", "C": "Ekonomik bütünleşme sağlamak", "D": "Askeri ittifak kurmak"},
     "dogru_cevap": "B", "aciklama": "Ortak kültürel ögeler Türk dünyasında kültürel kimliği ve kardeşliği güçlendirir."},
    {"unite": U3, "konu": "Türkistan'da Kurulan Türk Devletleri", "yil": 2024, "zorluk": "Orta",
     "soru": "İlk Türk devletlerinde;\nI. Hakan hem devlet başkanı hem ordu komutanı\nII. Kurultay'da önemli kararlar alınır\nIII. Boy beyleri yönetimde söz sahibi\n\nBu özellikler hangi yönetim anlayışını gösterir?",
     "siklar": {"A": "Mutlak monarşi", "B": "Federatif ve meşveret (danışma) yapısı", "C": "Demokrasi", "D": "Teokrasi"},
     "dogru_cevap": "B", "aciklama": "Kurultay ve boy beylerinin söz sahibi olması federatif ve danışma yapısını gösterir."},
    {"unite": U3, "konu": "İslam Medeniyetinin Ortak Mirası", "yil": 2024, "zorluk": "Zor",
     "soru": "İslam mimarisinde;\nI. Camiler\nII. Medreseler\nIII. Kervansaraylar\nIV. Darüşşifalar (hastaneler)\n\nBu yapılar birlikte değerlendirildiğinde İslam medeniyetinin hangi özelliği ortaya çıkar?",
     "siklar": {"A": "Sadece askeri güce önem vermesi", "B": "Eğitim, sağlık, ibadet ve ticaret gibi toplumsal ihtiyaçlara bütüncül yaklaşması", "C": "Yalnızca dini yapılar inşa etmesi", "D": "Mimariyle ilgilenmemesi"},
     "dogru_cevap": "B", "aciklama": "Cami, medrese, kervansaray ve darüşşifa toplumsal ihtiyaçlara bütüncül yaklaşımı gösterir."},
    {"unite": U3, "konu": "Askeri Mücadelelerin Anadolu'ya Etkileri", "yil": 2024, "zorluk": "Orta",
     "soru": "Anadolu'da kurulan Türk beylikleri;\nI. Camiler ve medreseler inşa etmiş\nII. Türkçeyi resmi dil olarak kullanmış\nIII. Sanat ve mimarlık alanında eserler vermiş\n\nBu bilgilere göre beylikler hangisine katkıda bulunmuştur?",
     "siklar": {"A": "Anadolu'nun boşaltılmasına", "B": "Anadolu'nun Türkleşmesi ve İslamlaşması sürecine", "C": "Bizans'ın güçlenmesine", "D": "Moğol hakimiyetinin artmasına"},
     "dogru_cevap": "B", "aciklama": "Beylikler Türkçe, İslam eğitimi ve mimari ile Anadolu'nun Türkleşmesine katkı sağlamıştır."},
    {"unite": U4, "konu": "Yönetim ve Karar Alma Süreci", "yil": 2024, "zorluk": "Zor",
     "soru": "Kuvvetler ayrılığı ilkesine göre;\nI. Yasama → TBMM\nII. Yürütme → Cumhurbaşkanı ve Kabine\nIII. Yargı → Bağımsız mahkemeler\n\nBu ilkenin amacı hangisidir?",
     "siklar": {"A": "Yönetimi zorlaştırmak", "B": "Gücün tek elde toplanmasını önleyerek hakları korumak", "C": "Devleti zayıflatmak", "D": "Sadece yargının güçlü olmasını sağlamak"},
     "dogru_cevap": "B", "aciklama": "Kuvvetler ayrılığı gücün tek elde toplanmasını önleyerek hakları korur."},
    {"unite": U4, "konu": "Dijitalleşme ve Vatandaşlık Bilinci", "yil": 2023, "zorluk": "Orta",
     "soru": "ALO 183 sosyal destek hattı, ihtiyaç sahiplerinin devlet yardımlarına erişimini kolaylaştırır.\n\nBu hizmet hangi devlet anlayışının göstergesidir?",
     "siklar": {"A": "Otoriter devlet", "B": "Sosyal devlet", "C": "Liberal devlet", "D": "Federal devlet"},
     "dogru_cevap": "B", "aciklama": "İhtiyaç sahiplerine destek sağlamak sosyal devlet anlayışının göstergesidir."},
    {"unite": U5, "konu": "Ekonomik Faaliyetler ve Meslekler", "yil": 2024, "zorluk": "Orta",
     "soru": "Bir çiftçi ürettiği domatesi;\n- Toptancı halinde satmış (toptancılık)\n- Tüccar markete satmış (perakende)\n- Tüketici marketten almış (tüketim)\n\nBu süreç hangisini gösterir?",
     "siklar": {"A": "Üretimden tüketime ekonomik döngüyü", "B": "Sadece tarım faaliyetini", "C": "İthalat sürecini", "D": "Bankacılık işlemini"},
     "dogru_cevap": "A", "aciklama": "Üretici→toptancı→perakendeci→tüketici ekonomik döngünün aşamalarıdır."},
    {"unite": U5, "konu": "Yatırım ve Pazarlama Süreci", "yil": 2024, "zorluk": "Zor",
     "soru": "Vergi;\nI. Devletin gelir kaynağıdır\nII. Kamu hizmetlerinin finansmanını sağlar\nIII. Bireysel kazançtır\n\nVergi hakkında hangileri doğrudur?",
     "siklar": {"A": "Yalnız I", "B": "I ve II", "C": "Yalnız III", "D": "I, II ve III"},
     "dogru_cevap": "B", "aciklama": "Vergi devletin gelir kaynağı ve kamu hizmetlerinin finansman aracıdır. Bireysel kazanç değildir."},
    {"unite": U5, "konu": "Ekonomik Faaliyetler ve Meslekler", "yil": 2023, "zorluk": "Zor",
     "soru": "Bir ülkenin Gayri Safi Yurt İçi Hasılası (GSYH) o ülkede üretilen toplam mal ve hizmetlerin değeridir.\n\nGSYH'nin yüksek olması hangisini gösterir?",
     "siklar": {"A": "Ülkenin borçlu olduğunu", "B": "Ekonomik üretim ve gelir düzeyinin yüksek olduğunu", "C": "İthalatın ihracattan fazla olduğunu", "D": "Nüfusun az olduğunu"},
     "dogru_cevap": "B", "aciklama": "Yüksek GSYH ekonomik üretim ve gelir düzeyinin yüksek olduğunu gösterir."},
    {"unite": U6, "konu": "Ulaşım ve İletişim Teknolojileri", "yil": 2024, "zorluk": "Orta",
     "soru": "Yapay zekâ destekli çeviri programları farklı dillerdeki insanların iletişim kurmasını kolaylaştırır.\n\nBu teknolojinin en önemli katkısı hangisidir?",
     "siklar": {"A": "Dil öğrenmeyi gereksiz kılması", "B": "Kültürler arası iletişim engellerini azaltması", "C": "Tüm dillerin aynı olmasını sağlaması", "D": "Sadece yazılı iletişimde kullanılması"},
     "dogru_cevap": "B", "aciklama": "Çeviri teknolojileri kültürler arası iletişim engellerini azaltmaya katkı sağlar."},
    {"unite": U6, "konu": "Telif ve Patent Süreci", "yil": 2023, "zorluk": "Zor",
     "soru": "Creative Commons (CC) lisansı;\nI. Eseri belirli koşullarla paylaşmaya izin verir\nII. Tüm hakları saklı tutar\nIII. Eser sahibinin adının belirtilmesini şart koşabilir\n\nBunlardan hangileri CC lisansının özelliğidir?",
     "siklar": {"A": "Yalnız I", "B": "I ve III", "C": "Yalnız II", "D": "I, II ve III"},
     "dogru_cevap": "B", "aciklama": "CC lisansı koşullu paylaşım ve atıf zorunluluğu özelliklerine sahiptir."},
    {"unite": U1, "konu": "Toplumsal Birliktelik", "yil": 2023, "zorluk": "Orta",
     "soru": "Spor müsabakalarında milli takımı desteklemek, zafer kutlamalarına katılmak toplumsal birlikteliği güçlendirir.\n\nBu etkinliklerin ortak özelliği hangisidir?",
     "siklar": {"A": "Yalnızca gençleri ilgilendirmesi", "B": "Milli duyguları ve toplumsal aidiyet bilincini güçlendirmesi", "C": "Sporcuları ödüllendirmesi", "D": "Ekonomik kazanç sağlaması"},
     "dogru_cevap": "B", "aciklama": "Milli takım destekle birlikte kutlamalar milli duygular ve aidiyet bilincini güçlendirir."},
    {"unite": U2, "konu": "Katman ve Oluşumları Koruma", "yil": 2023, "zorluk": "Zor",
     "soru": "Sürdürülebilir kalkınma;\nI. Doğal kaynakları koruyarak kullanma\nII. Gelecek nesillerin ihtiyaçlarını gözetme\nIII. Sınırsız tüketim yapma\nilkelerinden hangilerini kapsar?",
     "siklar": {"A": "Yalnız I", "B": "I ve II", "C": "Yalnız III", "D": "I, II ve III"},
     "dogru_cevap": "B", "aciklama": "Sürdürülebilir kalkınma kaynakları koruyarak kullanmayı ve gelecek nesilleri gözetmeyi kapsar."},
    {"unite": U3, "konu": "İslamiyet ile Türklerde Değişim", "yil": 2024, "zorluk": "Orta",
     "soru": "Selçuklular döneminde Nizamiye Medreseleri kurulmuştur. Bu medreseler sistemli eğitim veren ilk kurumlardan sayılır.\n\nNizamiye Medreselerinin en önemli yeniliği hangisidir?",
     "siklar": {"A": "Sadece askerlere eğitim vermesi", "B": "Planlı müfredat ve burslu öğrenci sistemiyle eğitimi kurumsal hale getirmesi", "C": "Yalnızca dini eğitim vermesi", "D": "Kadınlara eğitim yasaklaması"},
     "dogru_cevap": "B", "aciklama": "Nizamiye Medreseleri planlı müfredat ve burslu öğrenci ile eğitimi kurumsal hale getirmiştir."},
    {"unite": U4, "konu": "Temel Hak ve Sorumluluklar", "yil": 2024, "zorluk": "Zor",
     "soru": "Bir toplumda;\n- Kadınlar ve erkekler eşit ücret alıyor\n- Engelli bireyler için erişilebilirlik sağlanıyor\n- Her çocuk ücretsiz eğitim alabiliyor\n\nBu uygulamalar hangi devlet anlayışının göstergesidir?",
     "siklar": {"A": "Totaliter devlet", "B": "Sosyal hukuk devleti", "C": "Feodal devlet", "D": "Tek parti devleti"},
     "dogru_cevap": "B", "aciklama": "Eşit ücret, erişilebilirlik ve ücretsiz eğitim sosyal hukuk devleti anlayışının göstergeleridir."},
    {"unite": U5, "konu": "Yatırım ve Pazarlama Süreci", "yil": 2023, "zorluk": "Orta",
     "soru": "Tüketici hakları;\nI. Satın aldığı ürünü iade etme hakkı\nII. Bilgilendirilme hakkı\nIII. Sağlıklı ürün kullanma hakkı\nBunların korunması neden önemlidir?",
     "siklar": {"A": "Üreticilerin kâr etmesi için", "B": "Tüketicilerin haksızlığa uğramaması ve piyasada güvenin sağlanması için", "C": "Devletin gelir elde etmesi için", "D": "Reklamların artması için"},
     "dogru_cevap": "B", "aciklama": "Tüketici hakları haksızlığa karşı koruma ve piyasa güveni sağlar."},
    {"unite": U6, "konu": "Ulaşım ve İletişim Teknolojileri", "yil": 2023, "zorluk": "Orta",
     "soru": "Telemedicine (uzaktan tıp) sayesinde kırsal bölgelerdeki hastalar büyük şehirlerdeki uzman doktorlardan danışmanlık alabilmektedir.\n\nBu uygulamanın en önemli katkısı hangisidir?",
     "siklar": {"A": "Doktorların işsiz kalması", "B": "Sağlık hizmetlerinde fırsat eşitliğinin artması", "C": "Hastanelerin kapanması", "D": "İlaç kullanımının azalması"},
     "dogru_cevap": "B", "aciklama": "Uzaktan tıp sağlık hizmetlerinde coğrafi engelleri kaldırarak fırsat eşitliği sağlar."},
    {"unite": U1, "konu": "Toplumsal Sorunlar ve Çözümler", "yil": 2023, "zorluk": "Zor",
     "soru": "Toplumsal sorunların çözümünde;\nI. Devlet kurumları\nII. Sivil toplum kuruluşları\nIII. Bireyler\n\nHangileri sorumluluk sahibidir?",
     "siklar": {"A": "Yalnız I", "B": "I ve II", "C": "Yalnız III", "D": "I, II ve III"},
     "dogru_cevap": "D", "aciklama": "Toplumsal sorunların çözümünde devlet, sivil toplum ve bireyler birlikte sorumluluk taşır."},
    {"unite": U2, "konu": "Doğal ve Beşeri Özellikler", "yil": 2023, "zorluk": "Orta",
     "soru": "Türkiye'de üç tarafı denizlerle çevrili olması;\nI. Deniz ticaretini geliştirmiştir\nII. Kıyı turizmini artırmıştır\nIII. Balıkçılığı yaygınlaştırmıştır\n\nBu sonuçların tümü hangisiyle ilişkilidir?",
     "siklar": {"A": "Beşeri faaliyetlerle", "B": "Coğrafi konumun ekonomik faaliyetlere etkisiyle", "C": "İklim değişikliğiyle", "D": "Nüfus artışıyla"},
     "dogru_cevap": "B", "aciklama": "Denizlerle çevrili olmak ticaret, turizm ve balıkçılığı etkileyen coğrafi konum avantajıdır."},
    {"unite": U3, "konu": "Askeri Mücadelelerin Anadolu'ya Etkileri", "yil": 2022, "zorluk": "Orta",
     "soru": "Haçlı Seferleri'nden dönen Avrupalılar Doğu'dan pusula, barut, kâğıt gibi buluşları öğrenmiştir.\n\nBu durum hangisini gösterir?",
     "siklar": {"A": "Avrupalıların Doğu'yu tamamen fethettiklerini", "B": "Savaşların dolaylı olarak kültürel ve teknolojik etkileşime yol açtığını", "C": "Doğu'nun bu buluşlardan yararlanamadığını", "D": "Avrupalıların kendi başlarına her şeyi bulduğunu"},
     "dogru_cevap": "B", "aciklama": "Haçlı Seferleri savaş amaçlı olsa da kültürel ve teknolojik etkileşimi artırmıştır."},
    {"unite": U4, "konu": "Yönetim ve Karar Alma Süreci", "yil": 2022, "zorluk": "Orta",
     "soru": "Bir okuldaki öğrenci meclisi toplantısında öğrenciler sorunlarını belirlemiş ve çözüm önerileri sunmuştur.\n\nBu uygulama hangisine katkı sağlar?",
     "siklar": {"A": "Öğrencilerin ders başarısının düşmesine", "B": "Demokratik katılım bilincinin gelişmesine", "C": "Okul yönetiminin zayıflamasına", "D": "Öğrencilerin otoriteye karşı gelmesine"},
     "dogru_cevap": "B", "aciklama": "Öğrenci meclisi demokratik katılım bilincinin erken yaşta kazanılmasına katkı sağlar."},
    {"unite": U5, "konu": "Ekonomik Faaliyetler ve Meslekler", "yil": 2022, "zorluk": "Zor",
     "soru": "Serbest piyasa ekonomisinde;\nI. Arz ve talep fiyatı belirler\nII. Devlet tüm fiyatları sabitler\nIII. Özel girişim teşvik edilir\n\nSerbest piyasa ekonomisinin özellikleri hangileridir?",
     "siklar": {"A": "Yalnız I", "B": "I ve III", "C": "Yalnız II", "D": "I, II ve III"},
     "dogru_cevap": "B", "aciklama": "Serbest piyasada arz-talep fiyatı belirler ve özel girişim teşvik edilir. Devlet fiyatları sabitlemez."},
    {"unite": U6, "konu": "Ulaşım ve İletişim Teknolojileri", "yil": 2022, "zorluk": "Zor",
     "soru": "Blockchain teknolojisi;\nI. Verilerin güvenli şekilde saklanmasını sağlar\nII. Aracı kurumları ortadan kaldırabilir\nIII. Dijital para birimlerinin temelini oluşturur\n\nBu teknoloji hangi alanları etkilemektedir?",
     "siklar": {"A": "Sadece bankacılık", "B": "Finans, güvenlik ve dijital teknoloji", "C": "Sadece eğlence", "D": "Sadece tarım"},
     "dogru_cevap": "B", "aciklama": "Blockchain finans, güvenlik ve dijital teknoloji alanlarını etkileyen yenilikçi bir teknolojidir."},
    {"unite": U1, "konu": "Gruplar ve Roller", "yil": 2022, "zorluk": "Orta",
     "soru": "Bir afet durumunda;\n- İtfaiye yangını söndürür\n- AFAD koordinasyonu sağlar\n- Sağlık ekipleri yaralılara müdahale eder\n- Vatandaşlar yardım gönderir\n\nBu organizasyon hangisini gösterir?",
     "siklar": {"A": "Herkesin aynı işi yaptığını", "B": "Farklı kurumların iş birliği içinde çalışmasının önemini", "C": "Sadece devletin sorumlu olduğunu", "D": "Vatandaşların yardıma gerek olmadığını"},
     "dogru_cevap": "B", "aciklama": "Afette farklı kurumların ve vatandaşların iş birliği kritik önem taşır."},
    {"unite": U2, "konu": "Katman ve Oluşumları Koruma", "yil": 2022, "zorluk": "Orta",
     "soru": "Atık yağların lavaboya dökülmesi su kirliliğine neden olmaktadır. 1 litre atık yağ yaklaşık 1 milyon litre suyu kirletebilir.\n\nAtık yağlarla ilgili doğru davranış hangisidir?",
     "siklar": {"A": "Lavaboya dökmek", "B": "Atık yağ toplama noktalarına teslim etmek", "C": "Toprağa dökmek", "D": "Çöpe atmak"},
     "dogru_cevap": "B", "aciklama": "Atık yağlar toplama noktalarına teslim edilerek geri dönüşüme kazandırılmalıdır."},
    {"unite": U3, "konu": "İslam Medeniyetinin Ortak Mirası", "yil": 2023, "zorluk": "Orta",
     "soru": "İslam medeniyetinde vakıf sistemi; cami, medrese, hastane, çeşme gibi hizmetlerin topluma sunulmasını sağlamıştır.\n\nVakıf sisteminin toplumsal katkısı hangisidir?",
     "siklar": {"A": "Kâr amacı gütmesi", "B": "Sosyal dayanışmayı güçlendirmesi ve kamu yararına hizmet etmesi", "C": "Sadece zenginlere hizmet vermesi", "D": "Devlet bütçesini artırması"},
     "dogru_cevap": "B", "aciklama": "Vakıf sistemi sosyal dayanışmayı güçlendiren ve kamu yararına hizmet eden kurumdur."},
    {"unite": U4, "konu": "Dijitalleşme ve Vatandaşlık Bilinci", "yil": 2024, "zorluk": "Orta",
     "soru": "KPSS (Kamu Personeli Seçme Sınavı) ile devlet memurları liyakat esasına göre seçilir.\n\nLiyakat ilkesinin amacı hangisidir?",
     "siklar": {"A": "Tanıdığı olanların işe alınması", "B": "En nitelikli kişilerin göreve gelmesini sağlamak", "C": "Siyasi kayırmacılık yapmak", "D": "İşe alımı engellemek"},
     "dogru_cevap": "B", "aciklama": "Liyakat ilkesi en nitelikli kişilerin göreve gelmesini sağlayarak adaleti korur."},
    {"unite": U5, "konu": "Ekonomik Faaliyetler ve Meslekler", "yil": 2021, "zorluk": "Orta",
     "soru": "Meslek seçimi yaparken;\nI. İlgi ve yetenekleri dikkate almak\nII. Sadece para kazanmayı düşünmek\nIII. Toplumsal ihtiyaçları gözetmek\n\nDoğru meslek seçimi için hangileri önemlidir?",
     "siklar": {"A": "Yalnız II", "B": "I ve III", "C": "Yalnız I", "D": "I, II ve III"},
     "dogru_cevap": "B", "aciklama": "Doğru meslek seçiminde ilgi-yetenek ve toplumsal ihtiyaçlar birlikte gözetilmelidir."},
    {"unite": U6, "konu": "Telif ve Patent Süreci", "yil": 2022, "zorluk": "Orta",
     "soru": "Bir araştırmacı yeni bir ilaç formülü geliştirmiştir. Bu formülü;\nI. Patent ile korumuş\nII. Ticari sır olarak saklamış\nIII. Ücretsiz herkesle paylaşmış\n\nFikri mülkiyetin korunmasıyla ilgili olan hangisidir?",
     "siklar": {"A": "Yalnız I", "B": "I ve II", "C": "Yalnız III", "D": "I, II ve III"},
     "dogru_cevap": "B", "aciklama": "Patent ve ticari sır fikri mülkiyetin korunması yöntemleridir."},
]

out = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))), "data", "parts", "sorular_6_c.json")
with open(out, "w", encoding="utf-8") as f:
    json.dump(questions, f, ensure_ascii=False, indent=2)
print(f"6. Sınıf Batch C (Ek sorular): {len(questions)} soru yazıldı")
