#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Soru havuzu genişletici - Batch 1 (soru 1-100)"""
import json,os
Q=[]
def q(u,k,y,z,s,a,b,c,d,x,ac=""):
    Q.append({"id":len(Q)+1,"unite":u,"konu":k,"yil":y,"zorluk":z,"soru":s,"siklar":{"A":a,"B":b,"C":c,"D":d},"dogru_cevap":x,"aciklama":ac})
U1="Ünite 1 – Bir Kahraman Doğuyor"
U2="Ünite 2 – Millî Uyanış"
U3="Ünite 3 – Ya İstiklal Ya Ölüm"
U4="Ünite 4 – Çağdaş Türkiye Yolunda Adımlar"
U5="Ünite 5 – Atatürkçülük"
U6="Ünite 6 – Demokratikleşme Çabaları"
U7="Ünite 7 – Atatürk Dönemi Türk Dış Politikası"
# U1
q(U1,"Mustafa Kemal'in Öğrenim Hayatı",2018,"Kolay","Aşağıdakilerden hangisi Mustafa Kemal'in eğitim gördüğü okullardan biri değildir?","Şemsi Efendi Mektebi","Selanik Askerî Rüştiyesi","Galatasaray Sultanisi","Manastır Askerî İdadisi","C","Galatasaray Sultanisi'nde eğitim görmemiştir.")
q(U1,"Mustafa Kemal'in Askerlik Hayatı",2019,"Orta","Aşağıdakilerden hangisi Mustafa Kemal'in Çanakkale Savaşları'ndaki başarılarından biridir?","Sakarya'da geri çekilme emri","Anafartalar'da düşman çıkarmasını durdurması","Mudanya'yı imzalaması","TBMM'yi açması","B")
q(U1,"Mustafa Kemal'e Kemal Adı",2020,"Kolay","Mustafa Kemal'e 'Kemal' adını veren kişi kimdir?","Annesi Zübeyde Hanım","Babası Ali Rıza Efendi","Matematik öğretmeni","Şemsi Efendi","C")
q(U1,"Mustafa Kemal'in Kişiliği",2021,"Kolay","Mustafa Kemal'in liderlik vasfını en iyi yansıtan özellik hangisidir?","Müzik sevgisi","İleri görüşlülük ve kararlılık","Yüzme sporu","Kitap koleksiyonu","B")
q(U1,"Trablusgarp Savaşı",2017,"Orta","Mustafa Kemal'in ilk askerî başarısı hangi savaşta olmuştur?","Trablusgarp Savaşı","Çanakkale Savaşı","Sakarya Muharebesi","Büyük Taarruz","A")
q(U1,"Sofya Ataşemiliterliği",2023,"Zor","Mustafa Kemal'in Sofya Ataşemiliterliği ona hangi alanda en çok katkı sağlamıştır?","Askerî strateji","Diplomasi ve uluslararası ilişkiler","Ekonomi yönetimi","Eğitim reformları","B")
q(U1,"Mustafa Kemal'in Okul Seçimi",2016,"Kolay","Mustafa Kemal'in askerî okula gitme kararında kim etkili olmuştur?","Annesi","Komşu Binbaşı Kadri Bey","Babası","Öğretmeni","B")
q(U1,"I. Dünya Savaşı Cepheleri",2024,"Orta","Mustafa Kemal'in görev yaptığı cepheler arasında hangisi yoktur?","Çanakkale","Kafkas","Suriye-Filistin","Galiçya","D")
q(U1,"Mustafa Kemal'in Düşünceleri",2015,"Zor","'Benim naçiz vücudum elbet bir gün toprak olacaktır, fakat Türkiye Cumhuriyeti ilelebet payidar kalacaktır.' Bu söz neyi yansıtır?","Kişisel hırsları","Devleti bireyden üstün tutması","Askerî dehası","Ekonomi anlayışı","B")
q(U1,"Yurtta Sulh Cihanda Sulh",2022,"Orta","'Yurtta sulh, cihanda sulh' sözü Mustafa Kemal'in hangi özelliğini gösterir?","Savaşçılığını","Barışseverliğini","Ekonomi politikasını","Eğitim anlayışını","B")
# U2
q(U2,"I. Dünya Savaşı Nedenleri",2020,"Orta","I. Dünya Savaşı'nın çıkmasında sömürgecilik, bloklaşma ve milliyetçilikten hangileri etkilidir?","Yalnız I","Yalnız II","I ve II","I, II ve III","D")
q(U2,"Mondros Ateşkes Antlaşması",2021,"Orta","Mondros'un 7. maddesi İtilaf Devletleri'ne ne sağlamıştır?","Toprak bütünlüğünü koruma","Anadolu'yu işgal yolu","Asker sayısını artırma","Ekonomiyi güçlendirme","B")
q(U2,"Samsun'a Çıkış",2022,"Zor","Mustafa Kemal'in 19 Mayıs 1919'da Samsun'a çıkışının amacı nedir?","Saltanatı kaldırmak","Bölgedeki asayişsizliği incelemek ve millî bilinci uyandırmak","Cumhuriyeti ilan etmek","Halifeliği kaldırmak","B")
q(U2,"Amasya Genelgesi",2017,"Orta","'Vatanın bütünlüğü, milletin bağımsızlığı tehlikededir.' ifadesiyle ne amaçlanmıştır?","Savaş ilanı","Halkı bilinçlendirmek","Saltanatı kaldırmak","İstanbul'u desteklemek","B")
q(U2,"Erzurum Kongresi",2023,"Orta","'Millî sınırlar içinde vatan bir bütündür, parçalanamaz.' kararı neyi vurgular?","Bölgeselliği","Ulusal egemenliği","Vatanın bütünlüğünü","Saltanatın kaldırılmasını","C")
q(U2,"Sivas Kongresi",2016,"Kolay","Sivas Kongresi ile ilgili hangisi doğrudur?","Bölgeseldir","Yurdun çeşitli yerlerinden delegeler katılmıştır","Saltanat kaldırılmıştır","İstanbul düzenlemiştir","B")
q(U2,"Wilson İlkeleri",2015,"Orta","Wilson'ın 'Her millet kendi geleceğini belirlemelidir' ilkesi neyle ilişkilidir?","Sömürgecilik","Self-determinasyon","Emperyalizm","Mandacılık","B")
q(U2,"Çanakkale Cephesi",2019,"Orta","Osmanlı'nın I. Dünya Savaşı'nda yalnızca savunma amaçlı açtığı cephe hangisidir?","Kanal","Çanakkale","Kafkas","Hicaz","B")
q(U2,"Osmanlı'nın Savaşa Girişi",2020,"Zor","Osmanlı'nın İttifak yanında savaşa girmesinin temel nedeni nedir?","Almanya'nın ekonomik desteği","Kaybedilen toprakları geri alma düşüncesi","İngiltere'nin desteği","İtilaf ile ittifak","B")
q(U2,"Amasya Genelgesi Kararları",2021,"Zor","'Milletin istiklalini yine milletin azim ve kararı kurtaracaktır.' Bu karar neyin göstergesidir?","İstanbul'un desteklendiğinin","Millî iradeye dayalı mücadele anlayışının","Saltanatın kaldırılacağının","Ordunun güçlendirildiğinin","B")
q(U2,"Cemiyetler",2018,"Orta","Yararlı cemiyetlerin ortak amacı nedir?","Osmanlı'yı yeniden kurmak","Bölgelerini işgalden korumak","İstanbul'u desteklemek","Saltanatı güçlendirmek","B")
q(U2,"Kuva-yı Milliye",2022,"Orta","Kuva-yı Milliye birlikleri ile ilgili hangisi doğrudur?","Düzenli ordu","Halkın oluşturduğu direniş güçleri","İstanbul kurmuştur","Yalnız Batı Anadolu'da","B")
q(U2,"Paris Barış Konferansı",2023,"Orta","Paris Konferansı'nda İzmir'in Yunanlara verilmesi kararı neyi gösterir?","Wilson İlkeleri uygulanmıştır","Galip devletlerin çıkarları ön plandadır","Osmanlı katılmıştır","Barışçıl çözüm bulunmuştur","B")
q(U2,"Sevr Antlaşması",2024,"Zor","TBMM'nin Sevr'i reddetme gerekçesi nedir?","Ekonomik maddeler","Bağımsızlık ve toprak bütünlüğünü yok etmesi","Askerî madde yokluğu","Yalnız İstanbul'u kapsaması","B")
q(U2,"Zararlı Cemiyetler",2016,"Kolay","Hangisi zararlı cemiyetlerdendir?","Kilikyalılar","Doğu Anadolu Müdafaa-i Hukuk","Mavri Mira","Trakya-Paşaeli","C")
q(U2,"Misak-ı Millî",2017,"Orta","Misak-ı Millî kararları ile ilgili hangisi doğrudur?","Saltanat kaldırılmıştır","Millî sınırlar içinde tam bağımsızlık savunulmuştur","Mandater yönetim kabul edilmiştir","Parçalanma onaylanmıştır","B")
q(U2,"İzmir'in İşgali",2019,"Kolay","İzmir'in işgalinde ilk kurşunu atan kimdir?","Şahin Bey","Sütçü İmam","Hasan Tahsin","Satı Bey","C")
q(U2,"Amasya Görüşmeleri",2020,"Orta","Amasya Görüşmeleri İstanbul Hükûmeti'nin hangi tutumunu gösterir?","Millî mücadeleyi reddettiğini","Temsil Heyeti'ni tanımaya başladığını","Savaşa devam edeceğini","İtilaf ile ittifak kurduğunu","B")
q(U2,"Mondros",2015,"Kolay","I. Dünya Savaşı sonunda Osmanlı'nın imzaladığı ateşkes hangisidir?","Sevr","Mondros","Lozan","Mudanya","B")
q(U2,"Havza Genelgesi",2021,"Kolay","Havza Genelgesi ile halktan ne istenmiştir?","Silahlanma","İşgalleri protesto mitingleri","İstanbul'a göç","Yeni devlet kurma","B")
q(U2,"İstanbul'un İşgali",2018,"Zor","16 Mart 1920'de İstanbul'un resmen işgal edilmesinin en önemli sonucu nedir?","Osmanlı ordusunun güçlenmesi","Mebusan Meclisi'nin dağıtılması ve TBMM'nin açılış sürecinin hızlanması","Saltanatın kaldırılması","Lozan görüşmelerinin başlaması","B")
q(U2,"Kuvâ-yı İnzibatiye",2023,"Orta","İstanbul Hükûmeti tarafından TBMM'ye karşı kurulan kuvvet hangisidir?","Kuva-yı Milliye","Kuva-yı Seyyare","Kuvâ-yı İnzibatiye","Düzenli Ordu","C")
# U3
q(U3,"TBMM'nin Açılması",2020,"Kolay","TBMM'nin Ankara'da açılma nedenleri arasında hangisi gösterilemez?","Ulaşım imkânları","İstanbul'a yakın olması","Güvenli konumu","Millî mücadeleye destek","B")
q(U3,"Gümrü Antlaşması",2019,"Orta","Gümrü Antlaşması'nın önemi nedir?","Son antlaşmadır","TBMM'nin ilk uluslararası antlaşmasıdır","Batı sınırı çizilmiştir","Kapitülasyonlar kalkmıştır","B")
q(U3,"Güney Cephesi",2018,"Kolay","Güney Cephesi'nde mücadeleyle ilgili olmayan şehir hangisidir?","Antep","Maraş","Urfa","Erzurum","D")
q(U3,"I. İnönü",2021,"Orta","I. İnönü Muharebesi'nin sonuçlarından hangisi doğrudur?","Mudanya imzalanmıştır","TBMM'ye güven artmıştır","Saltanat kalkmıştır","Lozan imzalanmıştır","B")
q(U3,"Sakarya",2022,"Zor","Sakarya öncesi Mustafa Kemal'e Başkomutanlık verilmesi neyin göstergesidir?","Meclis yetkisi sınırlandı","Ordu sivilden ayrıldı","Durumun ciddiyeti ve hızlı karar ihtiyacı","Saltanat yeniden kuruldu","C")
q(U3,"Büyük Taarruz",2023,"Orta","Mudanya Ateşkes Antlaşması ile ne gerçekleşmiştir?","Doğu sınırı kesinleşti","İstanbul ve Boğazlar savaşsız TBMM'ye bırakıldı","Kapitülasyonlar kalktı","Cumhuriyet ilan edildi","B")
q(U3,"Lozan",2024,"Zor","Lozan Antlaşması ile ilgili hangisi söylenebilir?","Yalnız askerî konular ele alındı","Siyasi ve ekonomik bağımsızlık sağlandı","Osmanlı devamı kabul edildi","Yabancı okullar kapatıldı","B")
q(U3,"Tekalif-i Milliye",2017,"Orta","Tekalif-i Milliye Emirleri'nin amacı nedir?","Meclis yetkilerini sınırlamak","Ordunun ihtiyaçlarını halkın desteğiyle karşılamak","Anayasa hazırlamak","İstanbul ile barış","B")
q(U3,"II. İnönü",2016,"Orta","'Milletin makûs talihini de yendiniz.' sözüyle ne vurgulanmıştır?","Ekonomik boyut","Milletin kötü kaderinin değiştirildiği","Rütbe yükseltilmesi","Savaşın bittiği","B")
q(U3,"TBMM Ayaklanmaları",2018,"Orta","TBMM'ye karşı çıkan ayaklanmaların temel nedeni nedir?","Halkın askerlikten kaçması","İstanbul ve işgal güçlerinin TBMM'yi etkisizleştirmek istemesi","Ekonomik buhran","Doğal afetler","B")
q(U3,"Düzenli Ordu",2020,"Kolay","Düzenli ordunun kurulma nedeni nedir?","Halk savaşmak istemedi","Kuva-yı Milliye'nin disiplin eksikliği ve yetersizliği","İtilaf baskısı","İstanbul emri","B")
q(U3,"Kütahya-Eskişehir",2021,"Zor","Kütahya-Eskişehir'de Sakarya'nın doğusuna çekilme neyi gösterir?","Savaş kaybedildi","Stratejik geri çekilme yapıldı","Ordu dağıldı","Barış görüşmeleri başladı","B")
q(U3,"Moskova Antlaşması",2022,"Orta","1921 Moskova Antlaşması'nın önemi nedir?","Batı sınırı çizildi","Doğu sınırı belirlenmiştir","Kapitülasyonlar kalktı","Saltanat kalktı","B")
q(U3,"Londra Konferansı",2023,"Zor","TBMM'nin Londra Konferansı'na katılma amacı nedir?","Sevr'i kabul etmek","Türk davasını uluslararası arenada duyurmak","İstanbul ile birleşmek","İngiltere ile ittifak","B")
q(U3,"Büyük Taarruz Tarihi",2015,"Kolay","Büyük Taarruz hangi tarihte başlamıştır?","26 Ağustos 1922","30 Ağustos 1922","9 Eylül 1922","11 Ekim 1922","A")
q(U3,"Mudanya İmzacısı",2019,"Kolay","Mudanya'yı Türk tarafında kim imzalamıştır?","Mustafa Kemal","Kâzım Karabekir","İsmet Paşa","Fevzi Çakmak","C")
q(U3,"Ankara Antlaşması",2024,"Orta","1921 Ankara Antlaşması'nın sonucu nedir?","Batı sınırı çizildi","Güney Cephesi kapandı","Kapitülasyonlar kalktı","Doğu sınırı belirlendi","B")
q(U3,"1921 Anayasası",2020,"Orta","1921 Anayasası ile ilgili hangisi doğrudur?","Ayrıntılı ve uzundur","Egemenliğin milletin olduğu belirtilmiştir","Saltanat korunmuştur","Çok partili sistemi öngörmüştür","B")
q(U3,"Sakarya Sonrası",2016,"Kolay","Sakarya Zaferi'nden sonra Mustafa Kemal'e hangi unvan verilmiştir?","Paşa","Başkomutan","Gazi ve Mareşal","Cumhurbaşkanı","C")
q(U3,"İstiklal Marşı",2022,"Kolay","İstiklal Marşı hangi yıl TBMM tarafından kabul edilmiştir?","1919","1920","1921","1923","C","İstiklal Marşı, 12 Mart 1921'de TBMM tarafından kabul edilmiştir. Sözleri Mehmet Akif Ersoy'a aittir.")
q(U3,"Lozan Görüşmeleri",2023,"Zor","Lozan'da en uzun tartışılan konu hangisidir?","Sınırlar","Kapitülasyonlar","Boğazlar","Savaş tazminatları","B","Lozan'da en çok kapitülasyonların kaldırılması konusu tartışılmıştır.")
q(U3,"TBMM'nin Özellikleri",2017,"Orta","TBMM açıldığında kabul edilen ilke hangisidir?","Güçler ayrılığı","Güçler birliği","Padişahın yetkisi","Mandater yönetim","B","TBMM açıldığında yasama ve yürütme yetkisi Meclis'te toplanmıştır (güçler birliği).")
# U4
q(U4,"Saltanatın Kaldırılması",2016,"Kolay","Saltanatın kaldırılmasının doğrudan sonucu nedir?","Cumhuriyet ilanı","Osmanlı Devleti hukuken sona ermiştir","Halifelik kalktı","Laiklik benimsendi","B")
q(U4,"Cumhuriyetin İlanı",2020,"Orta","Cumhuriyetin ilan edilmesinin temel nedeni aşağıdakilerden hangisidir?","Halifeliğin kaldırılması","Devletin yönetim şeklinin belirlenmesi ihtiyacı","Çok partili hayata geçiş","Ekonomik kalkınma","B")
q(U4,"Halifeliğin Kaldırılması",2022,"Orta","3 Mart 1924'te halifeliğin kaldırılmasının nedeni nedir?","Ekonomik baskı","Laikliğe geçiş ve rejim karşıtlarının halifeliği kullanması","Halkın isteği","Dış baskılar","B")
q(U4,"Tevhid-i Tedrisat",2024,"Orta","Tevhid-i Tedrisat Kanunu ile ne amaçlanmıştır?","Yükseköğretimi kapatmak","Eğitimi birleştirmek ve devlet kontrolüne almak","Yabancı okulları artırmak","Medreseleri güçlendirmek","B")
q(U4,"Harf İnkılabı",2018,"Kolay","1928 Harf İnkılabı'nın amaçları arasında hangisi yoktur?","Okuma-yazma oranını artırmak","Batı ile iletişimi kolaylaştırmak","Tarihî belgelerle bağı güçlendirmek","Eğitimi kolaylaştırmak","C")
q(U4,"Medeni Kanun",2015,"Kolay","1926 Medeni Kanunu ile ne gerçekleşmiştir?","Padişahlık kalktı","Kadın-erkek eşitliği hukuki güvenceye kavuştu","Latin harfleri kabul edildi","Hafta sonu tatili belirlendi","B")
q(U4,"Soyadı Kanunu",2019,"Kolay","1934'te kabul edilen Soyadı Kanunu'nun amacı nedir?","Nüfusu artırmak","Toplumsal düzeni sağlamak ve resmi işlemleri kolaylaştırmak","Dış politikayı güçlendirmek","Askerliği düzenlemek","B")
q(U4,"Takvim ve Saat Değişikliği",2021,"Kolay","Miladi takvim ve uluslararası saat sistemi hangi yıl kabul edilmiştir?","1923","1925","1928","1934","B","26 Aralık 1925'te miladi takvim ve uluslararası saat sistemi kabul edilmiştir.")
q(U4,"Kılık Kıyafet Kanunu",2017,"Orta","Şapka Kanunu ve kılık kıyafet düzenlemesi hangi alanla ilgilidir?","Ekonomi","Toplumsal modernleşme","Askerî reform","Dış politika","B")
q(U4,"Tekke ve Zaviyelerin Kapatılması",2020,"Orta","Tekke, zaviye ve türbelerin kapatılması hangi ilkeyle ilişkilidir?","Cumhuriyetçilik","Laiklik","Devletçilik","Milliyetçilik","B")
q(U4,"Ölçü ve Tartı Sistemi",2023,"Kolay","Uluslararası ölçü ve tartı sisteminin kabul edilme amacı nedir?","Vergi artırmak","Ticaret ve günlük hayatı kolaylaştırmak","Askeri güçlendirmek","Dış borç ödemek","B")
q(U4,"Ekonomik Alandaki Gelişmeler",2022,"Orta","1923 İzmir İktisat Kongresi'nin amacı nedir?","Savaş ilan etmek","Yeni Türk Devleti'nin ekonomi politikalarını belirlemek","Anayasa hazırlamak","Saltanatı kaldırmak","B")
q(U4,"Kabotaj Kanunu",2021,"Orta","1926 Kabotaj Kanunu ile ne sağlanmıştır?","Eğitim birliği","Türk karasularında deniz ticaretinin Türk vatandaşlarına verilmesi","Kadın hakları","Toprak reformu","B")
q(U4,"Türk Tarih Kurumu",2019,"Kolay","Türk Tarih Kurumu'nun kuruluş amacı nedir?","Dış politika belirlemek","Türk tarihini bilimsel yöntemlerle araştırmak","Orduyu güçlendirmek","Ekonomiyi kalkındırmak","B")
q(U4,"Türk Dil Kurumu",2020,"Kolay","Türk Dil Kurumu hangi amaçla kurulmuştur?","Yeni alfabe oluşturmak","Türk dilini sadeleştirmek ve geliştirmek","Yabancı dil öğretmek","Basın yayını denetlemek","B")
q(U4,"Aşar Vergisi",2024,"Zor","Aşar vergisinin kaldırılmasının temel nedeni nedir?","Devlet gelirini artırmak","Köylünün ekonomik yükünü hafifletmek","Sanayi sektörünü desteklemek","Dış ticaret dengesini sağlamak","B","Aşar vergisi köylüyü ezen ağır bir vergi olduğundan 1925'te kaldırılmıştır.")
q(U4,"Cumhuriyetin İlanı Tarihi",2015,"Kolay","Cumhuriyet hangi tarihte ilan edilmiştir?","1 Kasım 1922","29 Ekim 1923","3 Mart 1924","30 Ekim 1918","B")
# U5
q(U5,"Cumhuriyetçilik",2020,"Orta","'Egemenlik kayıtsız şartsız milletindir.' sözü hangi ilkeyle ilişkilidir?","Devletçilik","Cumhuriyetçilik","Laiklik","İnkılapçılık","B")
q(U5,"Milliyetçilik",2021,"Kolay","Atatürk'ün milliyetçilik anlayışı ile ilgili hangisi doğrudur?","Irk temeline dayanır","Birleştirici ve bütünleştiricidir","Yalnız Türk kökenliyi kapsar","Diğer milletleri dışlar","B")
q(U5,"Laiklik",2022,"Orta","Hangisi laiklik ilkesi doğrultusunda yapılmıştır?","Soyadı Kanunu","Halifeliğin kaldırılması","Türk Tarih Kurumu","Kabotaj Kanunu","B")
q(U5,"Halkçılık",2023,"Kolay","Halkçılık ilkesinin temel amacı nedir?","Devletin ekonomiye müdahalesi","Toplumda sınıf ayrımını ortadan kaldırmak","Gelenekleri korumak","Din-devlet ayrımı","B")
q(U5,"Devletçilik",2019,"Orta","1929 Buhranı sonrası devletçilik ilkesinin öne çıkma nedeni nedir?","Özel sektörün yeterli sermayeye sahip olmaması","Dış borçlar","Savaş sanayii","Fabrikaların yeterli olması","A")
q(U5,"İnkılapçılık",2017,"Kolay","İnkılapçılık ilkesi neyi ifade eder?","Düzeni değiştirmemek","Yenilikleri korumak ve çağa uygun gelişmeyi sürdürmek","Yalnız ekonomik değişiklik","Eski geleneklere dönmek","B")
q(U5,"Atatürk İlkeleri Bütünlüğü",2024,"Zor","Atatürk ilkelerinin en belirgin özelliği nedir?","Birbirinden bağımsız olmaları","Birbirini tamamlayan bir bütün oluşturmaları","Yalnız siyasi alanı kapsamaları","Değişmez kurallar olmaları","B")
q(U5,"Cumhuriyetçilik Uygulaması",2018,"Orta","Aşağıdakilerden hangisi cumhuriyetçilik ilkesinin bir uygulamasıdır?","Medeni Kanun","TBMM'nin açılması ve seçimler yapılması","Harf İnkılabı","Kabotaj Kanunu","B")
q(U5,"Milliyetçilik Uygulaması",2016,"Orta","Hangisi milliyetçilik ilkesiyle doğrudan ilişkilidir?","Halifeliğin kaldırılması","Türk Tarih ve Dil Kurumlarının kurulması","Tekkelerin kapatılması","Soyadı Kanunu","B")
q(U5,"Atatürk İlkeleri ve İnkılaplar",2020,"Zor","Bir inkılap birden fazla Atatürk ilkesiyle ilişkili olabilir. Tevhid-i Tedrisat Kanunu hangi ilkelerle ilişkilidir?","Yalnız laiklik","Laiklik ve halkçılık","Yalnız cumhuriyetçilik","Yalnız milliyetçilik","B","Tevhid-i Tedrisat hem laiklik (din eğitimi ayrımı) hem halkçılık (eğitimde fırsat eşitliği) ile ilişkilidir.")
# U6
q(U6,"Çok Partili Hayat",2022,"Zor","Terakkiperver Cumhuriyet Fırkası'nın kapatılma gerekçesi nedir?","Ekonomik itiraz","Şeyh Sait İsyanı ile ilişkilendirilmesi","Seçim hilesi","Meclis çoğunluğu","B")
q(U6,"Kadın Hakları",2023,"Kolay","Türk kadınına seçme ve seçilme hakkı hangi yıl verilmiştir?","1926","1930","1934","1938","C")
q(U6,"Serbest Cumhuriyet Fırkası",2021,"Orta","Serbest Cumhuriyet Fırkası kimin isteğiyle kurulmuştur?","Fethi Okyar","İsmet İnönü","Atatürk","Kâzım Karabekir","C","Atatürk, çok partili hayata geçişi denemek amacıyla yakın arkadaşı Fethi Okyar'dan bu partiyi kurmasını istemiştir.")
q(U6,"1924 Anayasası",2020,"Orta","1924 Anayasası ile ilgili hangisi doğrudur?","Padişahlık korunmuştur","Egemenliğin millete ait olduğu belirtilmiştir","Güçler birliği esastır","Çok partili sistem zorunlu kılınmıştır","B")
q(U6,"Kadın Hakları Kronolojisi",2019,"Kolay","Türk kadınına belediye seçimlerine katılma hakkı hangi yıl verilmiştir?","1926","1930","1934","1935","B")
q(U6,"Menemen Olayı",2018,"Zor","1930 Menemen Olayı neyin göstergesidir?","Ekonomik krizin","Rejim karşıtlarının hâlâ tehdit oluşturduğunun","Çok partili hayatın başarılı olduğunun","Dış politika sorunlarının","B")
q(U6,"Hukuk Alanında Gelişmeler",2024,"Orta","1926'da Medeni Kanun'un İsviçre'den alınmasının nedeni nedir?","İsviçre'nin baskısı","Türk toplumunun ihtiyaçlarına en uygun ve çağdaş hukuk sistemi olması","Ekonomik zorunluluk","Askeri iş birliği","B")
q(U6,"Çok Partili Hayata Geçiş",2015,"Orta","Türkiye'de çok partili hayata kalıcı olarak hangi yıl geçilmiştir?","1923","1930","1938","1946","D","Türkiye'de çok partili hayata kalıcı olarak 1946'da geçilmiştir.")
# U7
q(U7,"Montrö Sözleşmesi",2020,"Orta","1936 Montrö Sözleşmesi ile ilgili hangisi doğrudur?","Boğazlar yabancılara bırakıldı","Boğazlardaki Türk egemenliği tam olarak sağlandı","Boğazlar kapatıldı","Boğazlar Milletler Cemiyeti'ne devredildi","B")
q(U7,"Hatay Meselesi",2021,"Orta","Hatay'ın anavatana katılma süreci nasıl olmuştur?","Savaş yoluyla","Önce bağımsız devlet, sonra Türkiye'ye katılma","Lozan ile bırakılma","İngiltere'den alma","B")
q(U7,"Balkan Antantı ve Sadabat Paktı",2024,"Orta","Bu antlaşmaların ortak amacı nedir?","Ekonomik iş birliği","Bölgesel barış ve güvenliği sağlamak","Sömürge edinmek","Tek parti yönetimini güçlendirmek","B")
q(U7,"Atatürk'ün Vefatı",2019,"Kolay","Atatürk'ün vefat ettiği yer hangisidir?","Çankaya Köşkü","Dolmabahçe Sarayı","Anıtkabir","Topkapı Sarayı","B")
q(U7,"İsmet İnönü",2024,"Orta","Atatürk'ten sonra cumhurbaşkanı seçilen kişi kimdir?","Celal Bayar","Adnan Menderes","İsmet İnönü","Fevzi Çakmak","C")
q(U7,"Milletler Cemiyeti",2018,"Orta","Türkiye Milletler Cemiyeti'ne hangi yıl katılmıştır?","1923","1930","1932","1936","C","Türkiye 1932'de Milletler Cemiyeti'ne üye olarak uluslararası arenada yerini güçlendirmiştir.")
q(U7,"Nüfus Mübadelesi",2022,"Zor","1923'te Yunanistan ile yapılan nüfus mübadelesinin temel amacı nedir?","Nüfusu artırmak","Azınlık sorunlarını çözmek ve kalıcı barışı sağlamak","Ekonomik kalkınma","Askerî güç artırmak","B")
q(U7,"Balkan Antantı Üyeleri",2017,"Kolay","Balkan Antantı'na katılan devletler arasında hangisi yoktur?","Türkiye","Yunanistan","Bulgaristan","Romanya","C","Balkan Antantı: Türkiye, Yunanistan, Yugoslavya ve Romanya. Bulgaristan katılmamıştır.")
q(U7,"Sadabat Paktı Üyeleri",2016,"Kolay","Sadabat Paktı hangi bölge devletleri arasında imzalanmıştır?","Balkan devletleri","Türkiye, İran, Irak ve Afganistan","Avrupa devletleri","Arap devletleri","B")
q(U7,"Hatay Bağımsızlığı",2023,"Orta","Hatay Devleti hangi yıl bağımsız olmuştur?","1936","1937","1938","1939","C")

with open("/Users/talatkarasakal/Documents/Çark/batch1.json","w",encoding="utf-8") as f:
    json.dump(Q, f, ensure_ascii=False, indent=2)
print(f"Batch 1: {len(Q)} soru yazıldı.")
