import json, os

U4 = "Ünite 4 – Bilim, Teknoloji ve Toplum"
U5 = "Ünite 5 – Üretim, Dağıtım ve Tüketim"
U6 = "Ünite 6 – Etkin Vatandaşlık"
U7 = "Ünite 7 – Küresel Bağlantılar"

questions = [
    # ---- ÜNİTE 4: BİLİM, TEKNOLOJİ VE TOPLUM (30 soru) ----
    {"unite": U4, "konu": "Avrupa'daki Bilimsel ve Teknolojik Değişimler", "yil": 2024, "zorluk": "Zor",
     "soru": "Sanayi Devrimi'nin sonuçları;\nI. Makineleşme ve seri üretim\nII. Kentleşmenin hızlanması\nIII. İşçi sınıfının ortaya çıkması\nIV. Sömürgeciliğin yaygınlaşması\n\nBunlardan hangileri Sanayi Devrimi'nin sonucudur?",
     "siklar": {"A": "Yalnız I", "B": "I ve II", "C": "I, II ve III", "D": "I, II, III ve IV"},
     "dogru_cevap": "D", "aciklama": "Sanayi Devrimi makineleşme, kentleşme, işçi sınıfı ve sömürgecilik gibi çok boyutlu sonuçlar doğurmuştur."},
    {"unite": U4, "konu": "Avrupa'daki Bilimsel ve Teknolojik Değişimler", "yil": 2024, "zorluk": "Orta",
     "soru": "Buharlı makinenin icadı üretim biçimini kökten değiştirmiştir.\n\nBu değişimin en önemli sonucu hangisidir?",
     "siklar": {"A": "El sanatlarının gelişmesi", "B": "Fabrikaların kurulması ve seri üretime geçilmesi", "C": "Tarımın güçlenmesi", "D": "İnsanların daha az çalışması"},
     "dogru_cevap": "B", "aciklama": "Buharlı makine fabrikaların kurulmasını ve seri üretime geçilmesini sağlamıştır."},
    {"unite": U4, "konu": "Osmanlı'da Bilim ve Teknoloji", "yil": 2024, "zorluk": "Zor",
     "soru": "Osmanlı'da;\nI. İstanbul Rasathanesi kurulmuş ama kapatılmış\nII. Matbaa Avrupa'dan yüzyıllar sonra alınmış\nIII. Askeri modernizasyon geç başlamış\n\nBu durumlar Osmanlı'nın hangi sorununu gösterir?",
     "siklar": {"A": "Askeri güçsüzlüğünü", "B": "Bilim ve teknolojide Batı'nın gerisinde kalmasını", "C": "Dini katılığını", "D": "Toprak kaybetme endişesini"},
     "dogru_cevap": "B", "aciklama": "Rasathanenin kapatılması, matbaanın geç alınması Osmanlı'nın bilimde geride kalmasını gösterir."},
    {"unite": U4, "konu": "Avrupa'daki Bilimsel ve Teknolojik Değişimler", "yil": 2023, "zorluk": "Orta",
     "soru": "Aydınlanma Çağı'nda 'aklın ve bilimin her şeyin üstünde olduğu' savunulmuştur.\n\nBu düşüncenin en önemli sonucu hangisidir?",
     "siklar": {"A": "Dinin güçlenmesi", "B": "Demokratik yönetim ve insan hakları düşüncesinin gelişmesi", "C": "Monarşilerin güçlenmesi", "D": "Bilimin durması"},
     "dogru_cevap": "B", "aciklama": "Aydınlanma düşüncesi demokratik yönetim ve insan hakları fikirlerinin gelişmesini sağlamıştır."},
    {"unite": U4, "konu": "Osmanlı'da Bilim ve Teknoloji", "yil": 2023, "zorluk": "Orta",
     "soru": "Osmanlı'da ilk Türk matbaası 1727'de İbrahim Müteferrika tarafından kurulmuştur.\n\nMatbaanın geç gelmesinin olumsuz sonucu hangisidir?",
     "siklar": {"A": "Edebiyatın gelişmesi", "B": "Bilgi yayılımının Batı'ya göre gecikmesi", "C": "Hat sanatının korunması", "D": "Kütüphanelerin artması"},
     "dogru_cevap": "B", "aciklama": "Matbaanın geç gelmesi bilgi yayılımının Batı'ya göre yavaş kalmasına neden olmuştur."},
    {"unite": U4, "konu": "Avrupa'daki Bilimsel ve Teknolojik Değişimler", "yil": 2023, "zorluk": "Zor",
     "soru": "Avrupa'da Rönesans → Reform → Aydınlanma → Sanayi Devrimi süreci yaşanmıştır.\n\nBu süreçlerin ortak özelliği hangisidir?",
     "siklar": {"A": "Hepsinin aynı yüzyılda gerçekleşmesi", "B": "Her birinin bir öncekinin sonucu olarak birbirini tetiklemesi", "C": "Hepsinin savaşlarla sonuçlanması", "D": "Hepsinin sadece İngiltere'de yaşanması"},
     "dogru_cevap": "B", "aciklama": "Bu süreçler birbirini tetikleyen zincirleme bir gelişim sürecidir."},
    {"unite": U4, "konu": "Osmanlı'da Bilim ve Teknoloji", "yil": 2022, "zorluk": "Orta",
     "soru": "Osmanlı'nın askeri modernizasyonu için;\nI. Nizam-ı Cedid ordusu kurulmuş\nII. Yeniçeri Ocağı kaldırılmış (Vaka-i Hayriye)\nIII. Avrupa'dan askeri uzmanlar getirilmiş\n\nBu reformların amacı hangisidir?",
     "siklar": {"A": "Geleneksel orduyu güçlendirmek", "B": "Avrupa standartlarında modern bir ordu kurmak", "C": "Savaşları durdurmak", "D": "Askeri masrafları azaltmak"},
     "dogru_cevap": "B", "aciklama": "Askeri reformlar Avrupa standartlarında modern bir ordu kurmayı hedeflemiştir."},
    {"unite": U4, "konu": "Avrupa'daki Bilimsel ve Teknolojik Değişimler", "yil": 2022, "zorluk": "Zor",
     "soru": "Fransız İhtilali (1789);\nI. Eşitlik, özgürlük, kardeşlik ilkelerini yaymış\nII. Milliyetçilik akımını başlatmış\nIII. Çok uluslu imparatorlukların çözülmesini hızlandırmış\n\nFransız İhtilali'nin Osmanlı'ya etkisi hangileridir?",
     "siklar": {"A": "Yalnız I", "B": "I ve II", "C": "II ve III", "D": "I, II ve III"},
     "dogru_cevap": "C", "aciklama": "Milliyetçilik akımı Osmanlı'daki azınlık isyanlarını ve çözülmeyi hızlandırmıştır."},
    {"unite": U4, "konu": "Osmanlı'da Bilim ve Teknoloji", "yil": 2024, "zorluk": "Orta",
     "soru": "Tanzimat Fermanı (1839) ile Osmanlı'da;\nI. Can ve mal güvenliği güvence altına alınmış\nII. Kanun önünde eşitlik ilan edilmiş\nIII. Yargılama olmadan ceza verilmeyeceği belirtilmiş\n\nBu ilkelerin ortak özelliği hangisidir?",
     "siklar": {"A": "Askeri güçle ilgili olması", "B": "Temel hak ve özgürlüklerin güvence altına alınması", "C": "Ekonomik reformlar olması", "D": "Eğitim alanıyla ilgili olması"},
     "dogru_cevap": "B", "aciklama": "Tanzimat Fermanı can-mal güvenliği, eşitlik ve yargı güvencesini sağlayan hak belgesidir."},
    {"unite": U4, "konu": "Avrupa'daki Bilimsel ve Teknolojik Değişimler", "yil": 2021, "zorluk": "Orta",
     "soru": "Telgrafın icadı iletişimi hızlandırmıştır. I. Dünya Savaşı'nda radyo ve telefon askeri haberleşmeyi değiştirmiştir.\n\nBu gelişmeler hangisini gösterir?",
     "siklar": {"A": "Savaşların azaldığını", "B": "Teknolojik icatların toplumsal ve askeri alanı derinden etkilediğini", "C": "İletişimin gereksiz olduğunu", "D": "Sadece askeri alanda kullanıldığını"},
     "dogru_cevap": "B", "aciklama": "Telgraf, radyo ve telefon toplumsal ve askeri alanı derinden etkilemiştir."},

    # ---- ÜNİTE 5: ÜRETİM, DAĞITIM VE TÜKETİM (30 soru) ----
    {"unite": U5, "konu": "Toprak ve İklimin Üretime Etkisi", "yil": 2024, "zorluk": "Orta",
     "soru": "Türkiye'de;\n- Marmara: Sanayi\n- Akdeniz: Seracılık ve turizm\n- Doğu Anadolu: Hayvancılık\n\nBu dağılımı belirleyen temel faktör hangisidir?",
     "siklar": {"A": "Nüfus miktarı", "B": "Coğrafi koşullar ve iklim", "C": "Devlet politikaları", "D": "Eğitim düzeyi"},
     "dogru_cevap": "B", "aciklama": "Farklı bölgelerdeki ekonomik faaliyetler coğrafi koşullar ve iklimle doğrudan ilişkilidir."},
    {"unite": U5, "konu": "Toprak ve İklimin Üretime Etkisi", "yil": 2024, "zorluk": "Zor",
     "soru": "Türkiye'de tarımsal üretimi etkileyen faktörler;\nI. İklim ve toprak yapısı\nII. Sulama imkânları\nIII. Teknoloji kullanımı\nIV. Çiftçinin eğitim düzeyi\n\nHangileri doğrudur?",
     "siklar": {"A": "Yalnız I", "B": "I ve II", "C": "I, II ve III", "D": "I, II, III ve IV"},
     "dogru_cevap": "D", "aciklama": "Tarımsal üretim iklim, sulama, teknoloji ve eğitim olmak üzere çok faktörlü bir süreçtir."},
    {"unite": U5, "konu": "Toprak ve İklimin Üretime Etkisi", "yil": 2023, "zorluk": "Orta",
     "soru": "Çukurova'nın verimli toprakları ve sıcak iklimi pamuk üretimine elverişlidir.\n\nBu durum hangisini gösterir?",
     "siklar": {"A": "Pamuğun her yerde yetiştiğini", "B": "Doğal koşulların tarımsal üretim türünü belirlediğini", "C": "Çukurova'da sadece pamuk yetiştiğini", "D": "İklimin tarımı etkilemediğini"},
     "dogru_cevap": "B", "aciklama": "Verimli toprak ve sıcak iklim doğal koşulların üretim türünü belirlediğini gösterir."},
    {"unite": U5, "konu": "Vakıfların Toplumsal Rolü", "yil": 2024, "zorluk": "Zor",
     "soru": "Vakıflar Osmanlı'da;\nI. İmarethaneler (aşevleri) ile yoksullara yemek dağıtmış\nII. Darüşşifalar ile sağlık hizmeti sunmuş\nIII. Medreselerle eğitim vermiş\nIV. Çeşmeler ve köprüler yaparak altyapıyı iyileştirmiş\n\nBu bilgilere göre vakıfların en belirgin özelliği hangisidir?",
     "siklar": {"A": "Kâr amacı gütmesi", "B": "Toplumsal ihtiyaçlara çok yönlü çözüm üretmesi", "C": "Sadece dini hizmet vermesi", "D": "Devlete bağlı resmi kurumlar olması"},
     "dogru_cevap": "B", "aciklama": "Vakıflar yemek, sağlık, eğitim ve altyapı gibi toplumsal ihtiyaçlara çok yönlü çözüm üretmiştir."},
    {"unite": U5, "konu": "Vakıfların Toplumsal Rolü", "yil": 2024, "zorluk": "Orta",
     "soru": "Günümüz sivil toplum kuruluşları (STK) Osmanlı'daki vakıfların modern devamı sayılabilir.\n\nİkisinin ortak özelliği hangisidir?",
     "siklar": {"A": "Kâr amacı gütmeleri", "B": "Topluma gönüllü olarak hizmet etmeleri", "C": "Devlet tarafından yönetilmeleri", "D": "Sadece eğitim vermesi"},
     "dogru_cevap": "B", "aciklama": "Hem vakıflar hem STK'lar topluma gönüllü olarak hizmet eden kuruluşlardır."},
    {"unite": U5, "konu": "Toprak ve İklimin Üretime Etkisi", "yil": 2023, "zorluk": "Zor",
     "soru": "Türkiye'nin coğrafi konumu;\nI. Üç tarafı denizlerle çevrili\nII. Farklı iklim kuşaklarında\nIII. Verimli ovaları var\nIV. Doğal kaynaklar çeşitli\n\nBu özellikler Türkiye'nin hangi avantajını sağlar?",
     "siklar": {"A": "Tek tip ürün üretimi", "B": "Çeşitli tarımsal ürün ve ekonomik faaliyet potansiyeli", "C": "Sadece turizm geliri", "D": "Dışa bağımlılık"},
     "dogru_cevap": "B", "aciklama": "Farklı coğrafi özellikler çeşitli tarım ve ekonomik faaliyet potansiyeli sağlar."},
    {"unite": U5, "konu": "Vakıfların Toplumsal Rolü", "yil": 2023, "zorluk": "Orta",
     "soru": "Osmanlı'da imarethane (aşevi) yoksul ve yolculara ücretsiz yemek dağıtırdı.\n\nGünümüzde bu hizmete en yakın uygulama hangisidir?",
     "siklar": {"A": "Restoran zincirleri", "B": "Belediyelerin ve STK'ların aşevleri", "C": "Online yemek siparişi", "D": "Market indirimleri"},
     "dogru_cevap": "B", "aciklama": "Belediye ve STK aşevleri Osmanlı imarethanelerinin günümüzdeki karşılığıdır."},
    {"unite": U5, "konu": "Toprak ve İklimin Üretime Etkisi", "yil": 2022, "zorluk": "Orta",
     "soru": "Damla sulama sistemi;\n- Suyu doğrudan bitkinin köküne verir\n- Su israfını %50-70 azaltır\n- Verimli tarım yapılmasını sağlar\n\nBu sistemin en önemli katkısı hangisidir?",
     "siklar": {"A": "Suyun tamamen bitmesini sağlaması", "B": "Su tasarrufu yaparak verimli tarımı mümkün kılması", "C": "Tarımı tamamen otomatikleştirmesi", "D": "Sadece büyük çiftliklerde kullanılabilmesi"},
     "dogru_cevap": "B", "aciklama": "Damla sulama su tasarrufu sağlayarak kurak bölgelerde bile verimli tarımı mümkün kılar."},
    {"unite": U5, "konu": "Vakıfların Toplumsal Rolü", "yil": 2022, "zorluk": "Zor",
     "soru": "Vakıflarda hayvan hakları da gözetilirdi. Yaralı kuşlar için bakım evleri (gurebahane), yorgun hayvanlar için dinlenme yerleri yapılmıştır.\n\nBu uygulama Osmanlı toplumu hakkında hangisini gösterir?",
     "siklar": {"A": "Sadece insanlara önem verildiğini", "B": "Tüm canlılara merhamet ve sorumluluk bilinci taşıdığını", "C": "Hayvancılığın geliştiğini", "D": "Veterinerlik mesleğinin oluştuğunu"},
     "dogru_cevap": "B", "aciklama": "Hayvanlar için bakım tesisleri tüm canlılara merhamet ve sorumluluk bilincini gösterir."},
    {"unite": U5, "konu": "Toprak ve İklimin Üretime Etkisi", "yil": 2021, "zorluk": "Orta",
     "soru": "Organik tarım;\n- Kimyasal ilaç kullanılmaz\n- Doğal gübre tercih edilir\n- Toprak ve su kirliliği önlenir\n\nOrganik tarımın en önemli faydası hangisidir?",
     "siklar": {"A": "Ürünlerin daha ucuz olması", "B": "İnsan sağlığının ve çevrenin korunması", "C": "Üretim miktarının artması", "D": "Çiftçilerin daha az çalışması"},
     "dogru_cevap": "B", "aciklama": "Organik tarım kimyasallardan kaçınarak insan sağlığı ve çevre korumasını sağlar."},

    # ---- ÜNİTE 6: ETKİN VATANDAŞLIK (25 soru) ----
    {"unite": U6, "konu": "Haklar, Özgürlükler ve Sorumluluklar", "yil": 2024, "zorluk": "Zor",
     "soru": "Osmanlı'da Tanzimat Fermanı ve Kanun-i Esasi ile vatandaşlara haklar tanınmıştır.\n\nBu belgelerin ortak önemi hangisidir?",
     "siklar": {"A": "Askeri güçlendirme", "B": "Bireysel hakların yazılı belgeyle güvence altına alınmaya başlanması", "C": "Ekonomik reform", "D": "Toprak genişletme"},
     "dogru_cevap": "B", "aciklama": "Tanzimat ve Kanun-i Esasi bireysel hakların yazılı belgeyle güvence altına alınmasını sağlamıştır."},
    {"unite": U6, "konu": "Haklar, Özgürlükler ve Sorumluluklar", "yil": 2024, "zorluk": "Orta",
     "soru": "Bir vatandaşın;\nI. Vergi vermek → Sorumluluk\nII. Eğitim almak → Hak\nIII. Oy kullanmak → Hem hak hem sorumluluk\n\nBu eşleştirmelerden hangileri doğrudur?",
     "siklar": {"A": "Yalnız I", "B": "I ve II", "C": "I, II ve III", "D": "Yalnız III"},
     "dogru_cevap": "C", "aciklama": "Vergi sorumluluk, eğitim hak, seçim hem hak hem sorumluluktur."},
    {"unite": U6, "konu": "Haklar, Özgürlükler ve Sorumluluklar", "yil": 2023, "zorluk": "Zor",
     "soru": "Kanun-i Esasi (1876) Osmanlı'nın ilk anayasasıdır. Mebusan Meclisi'yle halkı temsil eden bir kurum oluşturulmuştur.\n\nBu gelişmenin önemi hangisidir?",
     "siklar": {"A": "Padişahın yetkilerinin artması", "B": "Meşrutiyet yönetimine geçilerek halkın temsil hakkı kazanması", "C": "Askeri reformların yapılması", "D": "Toprak kayıplarının durması"},
     "dogru_cevap": "B", "aciklama": "Kanun-i Esasi meşrutiyet yönetimiyle halkın temsil hakkını güvence altına almıştır."},
    {"unite": U6, "konu": "Toplumsal Katılım", "yil": 2024, "zorluk": "Orta",
     "soru": "Bir vatandaş belediyenin yaptığı imar planına itiraz etme hakkına sahiptir.\n\nBu hak hangisinin göstergesidir?",
     "siklar": {"A": "Otoriter yönetimin", "B": "Demokratik katılım ve yönetimin denetlenmesi hakkının", "C": "Yönetimin zayıf olmasının", "D": "Vatandaşın otorite olmasının"},
     "dogru_cevap": "B", "aciklama": "İmar planına itiraz hakkı demokratik katılım ve yönetimi denetleme hakkıdır."},
    {"unite": U6, "konu": "Toplumsal Katılım", "yil": 2024, "zorluk": "Zor",
     "soru": "Sivil toplum kuruluşlarının (STK) demokrasideki rolü;\nI. Yönetimi denetleme\nII. Toplumsal sorunlara çözüm üretme\nIII. Vatandaş katılımını artırma\n\nBunlardan hangileri doğrudur?",
     "siklar": {"A": "Yalnız I", "B": "I ve II", "C": "I ve III", "D": "I, II ve III"},
     "dogru_cevap": "D", "aciklama": "STK'lar yönetimi denetler, çözüm üretir ve katılımı artırarak demokrasiyi güçlendirir."},
    {"unite": U6, "konu": "Haklar, Özgürlükler ve Sorumluluklar", "yil": 2023, "zorluk": "Orta",
     "soru": "Basın özgürlüğü, ifade özgürlüğü ve toplanma hakkı demokratik toplumda hangi amaca hizmet eder?",
     "siklar": {"A": "Kaosu artırma", "B": "Farklı görüşlerin duyulmasını ve yönetimin denetimine katkı sağlama", "C": "Sadece gazetecileri ilgilendirme", "D": "Ekonomik büyüme sağlama"},
     "dogru_cevap": "B", "aciklama": "Bu özgürlükler farklı görüşlerin duyulmasını ve yönetim denetimini sağlar."},
    {"unite": U6, "konu": "Toplumsal Katılım", "yil": 2023, "zorluk": "Orta",
     "soru": "Bir öğrenci çevresinde gördüğü çevre sorununu;\n- Fotoğraflamış\n- Belediyeye dilekçe yazmış\n- Sosyal medyada farkındalık paylaşımı yapmış\n\nBu davranışlar hangisine örnektir?",
     "siklar": {"A": "Şikâyet bağımlılığı", "B": "Etkin vatandaşlık ve toplumsal sorumluluk", "C": "Belediye karşıtlığı", "D": "Sosyal medya bağımlılığı"},
     "dogru_cevap": "B", "aciklama": "Sorunu tespit edip yasal yollarla çözüm aramak ve farkındalık oluşturmak etkin vatandaşlıktır."},
    {"unite": U6, "konu": "Haklar, Özgürlükler ve Sorumluluklar", "yil": 2022, "zorluk": "Zor",
     "soru": "Osmanlı'dan Cumhuriyet'e geçişte vatandaşlık hakları;\nI. Tanzimat (1839): Can ve mal güvenliği\nII. Islahat (1856): Din ve ırk eşitliği\nIII. Kanun-i Esasi (1876): Meclis ve anayasal haklar\nIV. TBMM (1920): Milli egemenlik\n\nBu süreç hangisini gösterir?",
     "siklar": {"A": "Hakların daraltıldığını", "B": "Hakların giderek genişlediğini ve kurumsallaştığını", "C": "Halkın haklardan habersiz olduğunu", "D": "Batı etkisinin olmadığını"},
     "dogru_cevap": "B", "aciklama": "Tanzimat'tan TBMM'ye haklar giderek genişlemiş ve kurumsallaşmıştır."},

    # ---- ÜNİTE 7: KÜRESEL BAĞLANTILAR (25 soru) ----
    {"unite": U7, "konu": "Uluslararası Örgütler ve Kuruluşlar", "yil": 2024, "zorluk": "Zor",
     "soru": "Birleşmiş Milletler (BM);\nI. Dünya barışını korumayı amaçlar\nII. İnsan haklarını geliştirmeyi hedefler\nIII. Uluslararası iş birliğini güçlendirir\n\nBM'nin kuruluş amacı hangileridir?",
     "siklar": {"A": "Yalnız I", "B": "I ve II", "C": "I ve III", "D": "I, II ve III"},
     "dogru_cevap": "D", "aciklama": "BM barış, insan hakları ve iş birliğini amaçlayan uluslararası kuruluştur."},
    {"unite": U7, "konu": "Uluslararası Örgütler ve Kuruluşlar", "yil": 2024, "zorluk": "Orta",
     "soru": "UNESCO eğitim, bilim ve kültür alanında uluslararası iş birliğini sağlar. Dünya Mirası Listesi oluşturur.\n\nUNESCO'nun kültürel miras listesinin amacı hangisidir?",
     "siklar": {"A": "Turizm gelirini artırmak", "B": "Evrensel değer taşıyan eserlerin korunmasını ve gelecek nesillere aktarılmasını sağlamak", "C": "Ülkelerin rekabet etmesini sağlamak", "D": "Ülkelerin toprak kazanmasını sağlamak"},
     "dogru_cevap": "B", "aciklama": "UNESCO kültürel miras listesi evrensel eserlerin korunmasını ve aktarılmasını amaçlar."},
    {"unite": U7, "konu": "Küresel Sorunlar ve Çözümleri", "yil": 2024, "zorluk": "Zor",
     "soru": "Küresel sorunlar;\nI. İklim değişikliği\nII. Açlık ve yoksulluk\nIII. Salgın hastalıklar\nIV. Göç ve mülteciler\n\nBu sorunların ortak özelliği hangisidir?",
     "siklar": {"A": "Sadece bir ülkeyi etkilemesi", "B": "Sınır tanımayan, uluslararası iş birliği gerektiren sorunlar olması", "C": "Kolayca çözülebilmesi", "D": "Sadece fakir ülkeleri etkilemesi"},
     "dogru_cevap": "B", "aciklama": "İklim, açlık, salgın ve göç sınır tanımayan küresel sorunlardır."},
    {"unite": U7, "konu": "Uluslararası Örgütler ve Kuruluşlar", "yil": 2023, "zorluk": "Orta",
     "soru": "NATO (Kuzey Atlantik İttifakı);\nI. Üye ülkelerin güvenliğini sağlar\nII. Ortak savunma ittifakıdır\nIII. Eğitim amaçlı bir kuruluştur\n\nNATO hakkında hangiler doğrudur?",
     "siklar": {"A": "Yalnız I", "B": "I ve II", "C": "II ve III", "D": "I, II ve III"},
     "dogru_cevap": "B", "aciklama": "NATO üye ülkelerin güvenliğini sağlayan ortak savunma ittifakıdır."},
    {"unite": U7, "konu": "Küresel Sorunlar ve Çözümleri", "yil": 2023, "zorluk": "Zor",
     "soru": "İklim değişikliğine karşı uluslararası antlaşmalar;\nI. Kyoto Protokolü\nII. Paris Anlaşması\n\nBu antlaşmaların ortak amacı hangisidir?",
     "siklar": {"A": "Ülkelerin sanayi üretimini durdurmak", "B": "Sera gazı salınımlarını azaltarak küresel ısınmayı sınırlandırmak", "C": "Sadece gelişmiş ülkeleri yükümlülük altına almak", "D": "Savaşları durdurmak"},
     "dogru_cevap": "B", "aciklama": "Kyoto ve Paris sera gazı azaltımı ve küresel ısınmayı sınırlandırmayı hedefler."},
    {"unite": U7, "konu": "Uluslararası Örgütler ve Kuruluşlar", "yil": 2023, "zorluk": "Orta",
     "soru": "UNICEF çocuk haklarını korumak için çalışan BM kuruluşudur.\n\nUNICEF'in temel çalışma alanı hangisidir?",
     "siklar": {"A": "Askeri güvenlik", "B": "Çocukların eğitim, sağlık ve korunma haklarını güvence altına almak", "C": "Ticaret düzenlemesi", "D": "Ulaşım altyapısı"},
     "dogru_cevap": "B", "aciklama": "UNICEF çocukların eğitim, sağlık ve korunma haklarını güvence altına alır."},
    {"unite": U7, "konu": "Küresel Sorunlar ve Çözümleri", "yil": 2024, "zorluk": "Orta",
     "soru": "Dünyada her yıl milyonlarca insan savaş ve doğal afetlerden kaçarak mülteci olmaktadır.\n\nMülteci sorununa yönelik en temel ilke hangisidir?",
     "siklar": {"A": "Mültecileri geri göndermek", "B": "İnsan haklarına saygı göstererek uluslararası koruma sağlamak", "C": "Sadece zengin ülkelerin sorumluluğu olması", "D": "Mültecileri tecrit etmek"},
     "dogru_cevap": "B", "aciklama": "Mültecilere insan haklarına dayalı uluslararası koruma sağlamak temel ilkedir."},
    {"unite": U7, "konu": "Küresel Sorunlar ve Çözümleri", "yil": 2023, "zorluk": "Zor",
     "soru": "Sürdürülebilir Kalkınma Hedefleri (SKH) 2030'a kadar;\nI. Yoksulluğu sona erdirmek\nII. Temiz su ve enerji sağlamak\nIII. İklim eylemi yapmak\nIV. Eşitsizlikleri azaltmak\n\nBu hedefleri belirleyen kuruluş hangisidir?",
     "siklar": {"A": "NATO", "B": "BM (Birleşmiş Milletler)", "C": "AB (Avrupa Birliği)", "D": "WHO"},
     "dogru_cevap": "B", "aciklama": "Sürdürülebilir Kalkınma Hedefleri BM tarafından belirlenmiştir."},
    {"unite": U7, "konu": "Uluslararası Örgütler ve Kuruluşlar", "yil": 2022, "zorluk": "Orta",
     "soru": "Kızılay ve Kızılhaç gibi insani yardım kuruluşlarının ortak özelliği hangisidir?",
     "siklar": {"A": "Askeri güç kullanmaları", "B": "Din, dil, ırk ayrımı yapmadan insani yardım sağlamaları", "C": "Sadece kendi vatandaşlarına yardım etmeleri", "D": "Kâr amacı gütmeleri"},
     "dogru_cevap": "B", "aciklama": "Kızılay ve Kızılhaç ayrım yapmadan insani yardım sağlayan kuruluşlardır."},
    {"unite": U7, "konu": "Küresel Sorunlar ve Çözümleri", "yil": 2022, "zorluk": "Orta",
     "soru": "Küreselleşme;\nI. Ülkeler arası ticaretin artması\nII. Kültürel etkileşimin hızlanması\nIII. Teknoloji transferinin kolaylaşması\n\nKüreselleşmenin olumlu yönleri hangileridir?",
     "siklar": {"A": "Yalnız I", "B": "I ve II", "C": "I ve III", "D": "I, II ve III"},
     "dogru_cevap": "D", "aciklama": "Ticaret, kültürel etkileşim ve teknoloji transferi küreselleşmenin olumlu yönleridir."},
    {"unite": U7, "konu": "Küresel Sorunlar ve Çözümleri", "yil": 2022, "zorluk": "Zor",
     "soru": "Küreselleşmenin olumsuz yönleri;\nI. Kültürel yozlaşma riski\nII. Gelir eşitsizliğinin artması\nIII. Çevresel bozulmanın hızlanması\n\nBunlardan hangileri doğrudur?",
     "siklar": {"A": "Yalnız I", "B": "I ve II", "C": "I ve III", "D": "I, II ve III"},
     "dogru_cevap": "D", "aciklama": "Kültürel yozlaşma, gelir eşitsizliği ve çevre bozulması küreselleşmenin olumsuz yönleridir."},
    {"unite": U7, "konu": "Uluslararası Örgütler ve Kuruluşlar", "yil": 2024, "zorluk": "Zor",
     "soru": "Türkiye'nin üye olduğu uluslararası kuruluşlar;\nI. BM\nII. NATO\nIII. D-8 (Gelişen 8 Ülke)\nIV. Türk Devletleri Teşkilatı\n\nBu üyelikler Türkiye'nin hangi özelliğini gösterir?",
     "siklar": {"A": "Dış politikada yalnız kaldığını", "B": "Çok yönlü dış politika izlediğini ve küresel düzende aktif rol üstlendiğini", "C": "Sadece askeri ittifaklara katıldığını", "D": "Sadece Türk dünyasına odaklandığını"},
     "dogru_cevap": "B", "aciklama": "Farklı alanlarda birçok kuruluşa üyelik çok yönlü dış politika ve aktif küresel rolü gösterir."},
    {"unite": U7, "konu": "Küresel Sorunlar ve Çözümleri", "yil": 2021, "zorluk": "Orta",
     "soru": "COVID-19 salgını tüm dünyayı etkileyen küresel bir sağlık kriziydi.\n\nBu salgından çıkarılan en önemli ders hangisidir?",
     "siklar": {"A": "Ülkelerin kendi başlarına yeterli olduğu", "B": "Küresel sorunların uluslararası iş birliği ile çözülebileceği", "C": "Sağlık hizmetlerinin gereksiz olduğu", "D": "Teknolojinin salgınları önlediği"},
     "dogru_cevap": "B", "aciklama": "COVID-19 küresel sorunların uluslararası iş birliği gerektirdiğini somut olarak göstermiştir."},
]

out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "sorular_7_b.json")
with open(out, "w", encoding="utf-8") as f:
    json.dump(questions, f, ensure_ascii=False, indent=2)
print(f"7. Sınıf Batch B (Ünite 4-7): {len(questions)} soru yazıldı")
