"""Eksik soruları ekleyip, dağılımı dengeleyip, birleştirip exe yapar."""
import json, os, copy, random
random.seed(123)
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
DATA_DIR = os.path.join(PROJECT_ROOT, "data")

def add_and_balance(grade, new_qs):
    fn = os.path.join(DATA_DIR, f"sorular_{grade}.json")
    with open(fn,"r",encoding="utf-8") as f: qs = json.load(f)
    qs.extend(new_qs)
    # Shuffle options for balanced distribution
    keys = ["A","B","C","D"]
    for q in qs:
        correct_text = q["siklar"][q["dogru_cevap"]]
        opts = list(q["siklar"].values())
        random.shuffle(opts)
        q["siklar"] = {k:opts[i] for i,k in enumerate(keys)}
        for k in keys:
            if q["siklar"][k] == correct_text:
                q["dogru_cevap"] = k; break
    # Fine-tune balance
    dist = {k:[] for k in keys}
    for i,q in enumerate(qs): dist[q["dogru_cevap"]].append(i)
    for _ in range(100):
        counts = {k:len(v) for k,v in dist.items()}
        mx,mn = max(counts,key=counts.get), min(counts,key=counts.get)
        if counts[mx]-counts[mn]<=1: break
        idx = dist[mx].pop()
        q = qs[idx]
        ct = q["siklar"][q["dogru_cevap"]]
        tt = q["siklar"][mn]
        q["siklar"][q["dogru_cevap"]] = tt
        q["siklar"][mn] = ct
        q["dogru_cevap"] = mn
        dist[mn].append(idx)
    with open(fn,"w",encoding="utf-8") as f: json.dump(qs,f,ensure_ascii=False,indent=2)
    d = {k:sum(1 for q in qs if q["dogru_cevap"]==k) for k in keys}
    print(f"{grade}. Sinif: {len(qs)} soru | A={d['A']} B={d['B']} C={d['C']} D={d['D']}")
    return len(qs)

# 6. SINIF EK (16 soru)
U6 = {"U1":"Ünite 1 – Birlikte Yaşamak","U2":"Ünite 2 – Evimiz Dünya","U3":"Ünite 3 – Ortak Mirasımız","U4":"Ünite 4 – Yaşayan Demokrasimiz","U5":"Ünite 5 – Hayatımızdaki Ekonomi","U6":"Ünite 6 – Teknoloji ve Sosyal Bilimler"}
ek6 = [
 {"unite":U6["U1"],"konu":"Toplumsal Birliktelik","yil":2024,"zorluk":"Orta","soru":"Bir mahallede farklı kültürlerden insanlar birlikte iftar sofrası kurmuştur.\n\nBu uygulama hangisine katkı sağlar?","siklar":{"A":"Kültürel çatışmaya","B":"Toplumsal ayrışmaya","C":"Toplumsal kaynaşma ve hoşgörüye","D":"Ekonomik soruna"},"dogru_cevap":"C","aciklama":"Birlikte iftar toplumsal kaynaşma ve hoşgörüye katkı sağlar."},
 {"unite":U6["U1"],"konu":"Gruplar ve Roller","yil":2023,"zorluk":"Zor","soru":"Bir okuldaki öğretmenler kurulu toplantısında;\nI. Müdür gündem belirler\nII. Öğretmenler görüş bildirir\nIII. Karar oy birliğiyle alınır\n\nBu süreç hangisine örnektir?","siklar":{"A":"Otoriter yönetime","B":"Bireysel karara","C":"Demokratik yönetime","D":"Bürokratik işleme"},"dogru_cevap":"C","aciklama":"Görüş bildirme ve oy birliği demokratik yönetim sürecidir."},
 {"unite":U6["U2"],"konu":"Doğal ve Beşeri Özellikler","yil":2024,"zorluk":"Orta","soru":"Güneydoğu Anadolu'da kurak iklim nedeniyle sulama kanalları yapılmıştır.\n\nBu durum hangisini gösterir?","siklar":{"A":"İnsanın doğayı değiştirdiğini","B":"İklimin değişmediğini","C":"Sulamanın gereksiz olduğunu","D":"Tarımın yapılamadığını"},"dogru_cevap":"A","aciklama":"Sulama kanalları insanın doğal koşulları değiştirerek tarım yapmasını gösterir."},
 {"unite":U6["U2"],"konu":"Katman ve Oluşumları Koruma","yil":2023,"zorluk":"Zor","soru":"Ozon tabakasının incelmesi;\nI. Zararlı UV ışınlarının artmasına\nII. Cilt kanseri riskinin yükselmesine\nIII. Ekosistemin zarar görmesine\nyol açar.\n\nOzon tabakasını korumanın yolu hangisidir?","siklar":{"A":"Daha fazla fabrika açmak","B":"Fosil yakıt kullanımını artırmak","C":"Ozon tabakasına zarar veren kimyasalları azaltmak","D":"Daha fazla araç kullanmak"},"dogru_cevap":"C","aciklama":"Ozon tabakasını korumanın yolu zararlı kimyasalları azaltmaktır."},
 {"unite":U6["U3"],"konu":"Türkistan'da Kurulan Türk Devletleri","yil":2024,"zorluk":"Orta","soru":"Uygurlar yerleşik hayata geçen ilk Türk devletidir. Matbaa ve kağıdı kullanan ilk Türklerdir.\n\nBu bilgi Uygurlar hakkında hangisini gösterir?","siklar":{"A":"Savaşçı bir toplum olduklarını","B":"Göçebe yaşadıklarını","C":"Kültür ve medeniyette ileri olduklarını","D":"Tarımla uğraşmadıklarını"},"dogru_cevap":"C","aciklama":"Yerleşik hayat, matbaa ve kağıt kullanımı kültürel ilerlemeyi gösterir."},
 {"unite":U6["U3"],"konu":"İslam Medeniyetinin Ortak Mirası","yil":2023,"zorluk":"Orta","soru":"İbn-i Sina'nın 'El-Kanun fi't-Tıb' eseri yüzyıllarca Avrupa üniversitelerinde ders kitabı olarak okutulmuştur.\n\nBu bilgi hangisini gösterir?","siklar":{"A":"Avrupa'nın tıpta ileri olduğunu","B":"İslam bilginlerinin evrensel bilime büyük katkı sağladığını","C":"İbn-i Sina'nın Avrupalı olduğunu","D":"Tıbbın gelişmediğini"},"dogru_cevap":"B","aciklama":"İbn-i Sina'nın eserinin Avrupa'da okutulması İslam biliminin evrensel katkısını gösterir."},
 {"unite":U6["U4"],"konu":"Yönetim ve Karar Alma Süreci","yil":2024,"zorluk":"Zor","soru":"Yargı bağımsızlığı;\nI. Mahkemelerin hiçbir baskı altında olmadan karar vermesi\nII. Hakimlerin siyasi baskıdan korunması\n\nYargı bağımsızlığının önemi hangisidir?","siklar":{"A":"Suçluların korunması","B":"Yargının yavaşlaması","C":"Devletin güçlenmesi","D":"Adaletin tarafsız ve güvenilir şekilde sağlanması"},"dogru_cevap":"D","aciklama":"Yargı bağımsızlığı adaletin tarafsız ve güvenilir şekilde sağlanmasını güvence altına alır."},
 {"unite":U6["U4"],"konu":"Temel Hak ve Sorumluluklar","yil":2023,"zorluk":"Orta","soru":"Çocuk hakları;\nI. Eğitim hakkı\nII. Sağlık hakkı\nIII. Oyun ve dinlenme hakkı\nIV. Çalıştırılmama hakkı\n\nBu hakların korunması kimin sorumluluğundadır?","siklar":{"A":"Sadece ailenin","B":"Sadece devletin","C":"Sadece okulun","D":"Aile, devlet ve toplumun birlikte"},"dogru_cevap":"D","aciklama":"Çocuk hakları aile, devlet ve toplumun ortak sorumluluğundadır."},
 {"unite":U6["U5"],"konu":"Ekonomik Faaliyetler","yil":2024,"zorluk":"Orta","soru":"Bir ülkede ihracat ithalattan fazlaysa dış ticaret fazlası vardır.\n\nDış ticaret fazlasının ülke ekonomisine etkisi hangisidir?","siklar":{"A":"Ekonomiyi zayıflatması","B":"Döviz girdisini artırarak ekonomiyi güçlendirmesi","C":"İthalatı artırması","D":"İşsizliği artırması"},"dogru_cevap":"B","aciklama":"Dış ticaret fazlası döviz girdisini artırarak ekonomiyi güçlendirir."},
 {"unite":U6["U5"],"konu":"Yatırım ve Pazarlama","yil":2023,"zorluk":"Zor","soru":"Kooperatifler;\nI. Üreticilerin birlikte hareket etmesini sağlar\nII. Aracıları ortadan kaldırır\nIII. Üreticinin gelirini artırır\n\nKooperatiflerin en önemli faydası hangisidir?","siklar":{"A":"Üreticilerin birlikte güçlenerek adil gelir elde etmesi","B":"Tüketicilerin zarar görmesi","C":"Devletin gelirinin artması","D":"İthalatın artması"},"dogru_cevap":"A","aciklama":"Kooperatifler üreticileri güçlendirerek adil gelir elde etmelerini sağlar."},
 {"unite":U6["U6"],"konu":"Ulaşım ve İletişim","yil":2024,"zorluk":"Orta","soru":"3D yazıcı teknolojisi;\nI. Protez üretimi\nII. Mimari model yapımı\nIII. Yedek parça üretimi\n\nBu teknolojinin ortak katkısı hangisidir?","siklar":{"A":"Sadece oyuncak yapımı","B":"Üretimi kişiselleştirerek maliyetleri düşürmesi","C":"Sadece büyük fabrikalarda kullanılması","D":"Teknolojinin gerilemesi"},"dogru_cevap":"B","aciklama":"3D yazıcı üretimi kişiselleştirir ve maliyetleri düşürür."},
 {"unite":U6["U6"],"konu":"Telif ve Patent","yil":2022,"zorluk":"Zor","soru":"Açık kaynak yazılım;\nI. Kaynak kodu herkese açıktır\nII. Geliştirilmesine herkes katkıda bulunabilir\nIII. Genellikle ücretsizdir\n\nAçık kaynak yazılımın avantajı hangisidir?","siklar":{"A":"Her zaman güvensiz olması","B":"Sadece uzmanların kullanabilmesi","C":"Topluluk katkısıyla hızla gelişmesi ve şeffaf olması","D":"Ticari kullanıma kapalı olması"},"dogru_cevap":"C","aciklama":"Açık kaynak topluluk katkısıyla hızla gelişen şeffaf bir modeldir."},
 {"unite":U6["U1"],"konu":"Toplumsal Sorunlar","yil":2024,"zorluk":"Zor","soru":"Toplumda sosyal medya bağımlılığı artmaktadır.\n\nBu sorunla mücadele için en etkili yaklaşım hangisidir?","siklar":{"A":"Sosyal medyayı tamamen yasaklamak","B":"İnterneti kapatmak","C":"Dijital okuryazarlık eğitimi ve bilinçli kullanım alışkanlığı kazandırmak","D":"Sadece yetişkinlerin kullanmasına izin vermek"},"dogru_cevap":"C","aciklama":"Dijital okuryazarlık ve bilinçli kullanım en etkili mücadele yöntemidir."},
 {"unite":U6["U3"],"konu":"Askeri Mücadeleler","yil":2022,"zorluk":"Orta","soru":"Malazgirt Meydan Muharebesi (1071);\nI. Anadolu'nun kapıları Türklere açılmış\nII. Bizans'ın askeri gücü kırılmış\n\nMalazgirt'in en önemli sonucu hangisidir?","siklar":{"A":"Anadolu'nun Türk yurdu haline gelmesinin başlangıcı","B":"Bizans'ın güçlenmesi","C":"Haçlı Seferlerinin başlaması","D":"İslam'ın yayılması"},"dogru_cevap":"A","aciklama":"Malazgirt Anadolu'nun Türk yurdu haline gelmesinin başlangıcıdır."},
 {"unite":U6["U5"],"konu":"Ekonomik Faaliyetler","yil":2022,"zorluk":"Orta","soru":"Bütçe yönetimi;\nI. Gelir ve giderleri dengeli tutmak\nII. Tasarrufu alışkanlık haline getirmek\nIII. Her istediğini hemen almak\n\nDoğru bütçe yönetimi hangileridir?","siklar":{"A":"Yalnız III","B":"I ve II","C":"I ve III","D":"I, II ve III"},"dogru_cevap":"B","aciklama":"Doğru bütçe gelir-gider dengesi ve tasarruf alışkanlığı ile sağlanır."},
 {"unite":U6["U4"],"konu":"Dijitalleşme ve Vatandaşlık","yil":2024,"zorluk":"Orta","soru":"Kişisel verilerin korunması;\nI. KVKK (Kişisel Verilerin Korunması Kanunu) vatandaşları korur\nII. Şirketler izinsiz veri toplayamaz\n\nKVKK'nın amacı hangisidir?","siklar":{"A":"Şirketleri güçlendirmek","B":"Vatandaşların dijital ortamda güvenliğini ve mahremiyetini korumak","C":"İnterneti yavaşlatmak","D":"Devlet kontrolünü artırmak"},"dogru_cevap":"B","aciklama":"KVKK vatandaşların dijital güvenliğini ve mahremiyetini korur."},
]

# 7. SINIF EK (25 soru)
U7 = {"U1":"Ünite 1 – Birey ve Toplum","U2":"Ünite 2 – Kültür ve Miras","U3":"Ünite 3 – İnsanlar, Yerler ve Çevreler","U4":"Ünite 4 – Bilim, Teknoloji ve Toplum","U5":"Ünite 5 – Üretim, Dağıtım ve Tüketim","U6":"Ünite 6 – Etkin Vatandaşlık","U7":"Ünite 7 – Küresel Bağlantılar"}
ek7 = [
 {"unite":U7["U1"],"konu":"İletişim","yil":2024,"zorluk":"Orta","soru":"Topluluk önünde konuşma yaparken;\nI. Göz teması kurulmalı\nII. Açık ve anlaşılır cümleler kullanılmalı\nIII. Monoton bir ses tonu kullanılmalı\n\nEtkili sunum için hangileri doğrudur?","siklar":{"A":"I ve II","B":"II ve III","C":"Yalnız I","D":"I, II ve III"},"dogru_cevap":"A","aciklama":"Göz teması ve açık dil etkili sunumun temelidir. Monoton ses olumsuz etkiler."},
 {"unite":U7["U1"],"konu":"Medya","yil":2023,"zorluk":"Zor","soru":"Dijital ayak izi;\nI. İnternetteki tüm aktiviteler kaydedilir\nII. Paylaşılan bilgiler geri alınamayabilir\nIII. Gelecekte iş başvurularında incelenebilir\n\nDijital ayak izine karşı doğru tutum hangisidir?","siklar":{"A":"İnterneti hiç kullanmamak","B":"Her şeyi paylaşmak","C":"Paylaşmadan önce düşünmek ve dijital kimliği bilinçli yönetmek","D":"Sahte hesaplar kullanmak"},"dogru_cevap":"C","aciklama":"Dijital ayak izini yönetmenin en doğru yolu bilinçli paylaşımdır."},
 {"unite":U7["U2"],"konu":"Beylikten Cihan Devletine","yil":2024,"zorluk":"Orta","soru":"Osmanlı'da Enderun Mektebi;\nI. Devlet adamı yetiştirirdi\nII. Sanat ve bilim eğitimi verirdi\nIII. Seçkin öğrenciler alınırdı\n\nEnderun'un amacı hangisidir?","siklar":{"A":"Askeri güç oluşturmak","B":"Devlet yönetimi için nitelikli kadro yetiştirmek","C":"Dini eğitim vermek","D":"Ticaret yapmak"},"dogru_cevap":"B","aciklama":"Enderun devlet yönetimi için nitelikli kadro yetiştiren seçkin bir eğitim kurumuydu."},
 {"unite":U7["U2"],"konu":"Avrupa'da Uyanış","yil":2023,"zorluk":"Zor","soru":"Merkantilizm;\nI. Devlet zenginliğini altın-gümüş birikimiyle ölçer\nII. İhracatı teşvik, ithalatı kısıtlar\nIII. Sömürgelerin hammaddesi kullanılır\n\nMerkantilizmin sonucu hangisidir?","siklar":{"A":"Serbest ticaret","B":"Sömürgeciliğin güçlenmesi","C":"Küçük devletlerin zenginleşmesi","D":"Tarımın gelişmesi"},"dogru_cevap":"B","aciklama":"Merkantilizm hammadde ihtiyacı nedeniyle sömürgeciliği güçlendirmiştir."},
 {"unite":U7["U3"],"konu":"Nüfus","yil":2024,"zorluk":"Orta","soru":"Yaşlanan toplum;\nI. Emekli sayısı artar\nII. Sağlık harcamaları yükselir\nIII. İş gücü azalır\n\nBu soruna karşı alınabilecek önlem hangisidir?","siklar":{"A":"Emekliliği kaldırmak","B":"Göçü tamamen durdurmak","C":"Doğurganlığı teşvik eden politikalar ve emeklilik reformları uygulamak","D":"Sağlık hizmetlerini kısıtlamak"},"dogru_cevap":"C","aciklama":"Yaşlanan topluma karşı doğurganlık teşviki ve emeklilik reformları etkili önlemlerdir."},
 {"unite":U7["U3"],"konu":"İklim","yil":2023,"zorluk":"Zor","soru":"Yenilenebilir enerji kaynakları;\nI. Güneş\nII. Rüzgâr\nIII. Jeotermal\nIV. Hidroelektrik\n\nBu kaynakların fosil yakıtlara göre avantajı hangisidir?","siklar":{"A":"Daha pahalı olması","B":"Daha az enerji üretmesi","C":"Sera gazı salınımı yapmayarak çevreyi koruması","D":"Her yerde kullanılamaması"},"dogru_cevap":"C","aciklama":"Yenilenebilir kaynaklar sera gazı salınımı yapmayarak çevreyi korur."},
 {"unite":U7["U4"],"konu":"Avrupa'daki Değişimler","yil":2024,"zorluk":"Orta","soru":"Gutenberg'in matbaayı bulması (1450);\nI. Bilgi hızla yayılmış\nII. Kitap maliyeti düşmüş\nIII. Okuryazarlık artmış\n\nMatbaanın en devrimci etkisi hangisidir?","siklar":{"A":"Kâğıt israfını artırması","B":"Bilginin demokratikleşmesi ve kitlelere ulaşması","C":"Sadece dini metinlerin basılması","D":"El yazması kitapların artması"},"dogru_cevap":"B","aciklama":"Matbaa bilginin demokratikleşerek kitlelere ulaşmasını sağlamıştır."},
 {"unite":U7["U4"],"konu":"Osmanlı'da Bilim","yil":2023,"zorluk":"Orta","soru":"Osmanlı'da ilk kâğıt fabrikası 1744'te kurulmuştur. Avrupa'da ise 13. yüzyılda kâğıt üretimi başlamıştır.\n\nBu gecikme hangisini gösterir?","siklar":{"A":"Osmanlı'nın kâğıda ihtiyaç duymadığını","B":"Sanayi üretiminde Batı'nın gerisinde kalındığını","C":"Kâğıdın gereksiz olduğunu","D":"El yazmasının daha iyi olduğunu"},"dogru_cevap":"B","aciklama":"Kâğıt fabrikasının geç kurulması sanayi üretiminde geride kalındığını gösterir."},
 {"unite":U7["U5"],"konu":"Toprak ve İklim","yil":2024,"zorluk":"Zor","soru":"Türkiye'de;\nI. GAP (Güneydoğu Anadolu Projesi) → Sulama ve enerji\nII. Konya Ovası Projesi → Tarımsal sulama\nIII. DSİ barajları → Su yönetimi\n\nBu projelerin ortak amacı hangisidir?","siklar":{"A":"Sadece enerji üretmek","B":"Tarımsal verimliliği artırmak ve su kaynaklarını yönetmek","C":"Sanayi tesisleri kurmak","D":"Nüfusu azaltmak"},"dogru_cevap":"B","aciklama":"Bu projeler tarımsal verimliliği artırmayı ve su kaynaklarını yönetmeyi amaçlar."},
 {"unite":U7["U5"],"konu":"Vakıflar","yil":2023,"zorluk":"Orta","soru":"Günümüzde mikro kredi;\nI. Küçük girişimcilere düşük faizli kredi verir\nII. Yoksulluğu azaltmayı amaçlar\nIII. Muhammad Yunus Nobel Barış Ödülü almıştır\n\nMikro kredi hangisine benzer bir mantıkla çalışır?","siklar":{"A":"Büyük bankaların kredi sistemi","B":"Osmanlı vakıf sisteminin toplumsal dayanışma anlayışı","C":"Uluslararası ticaret","D":"Vergi sistemi"},"dogru_cevap":"B","aciklama":"Mikro kredi Osmanlı vakıf sisteminin toplumsal dayanışma ruhuna benzer."},
 {"unite":U7["U6"],"konu":"Haklar","yil":2024,"zorluk":"Orta","soru":"Bilgi edinme hakkı;\nI. Vatandaşlar devlet kurumlarından bilgi isteyebilir\nII. Şeffaflığı sağlar\nIII. Yönetimin denetlenmesine katkıda bulunur\n\nBu hakkın önemi hangisidir?","siklar":{"A":"Bürokrasiyi artırması","B":"Şeffaf yönetimi ve hesap verebilirliği güçlendirmesi","C":"Devlet sırlarını ifşa etmesi","D":"Vatandaşları bilgiyle boğması"},"dogru_cevap":"B","aciklama":"Bilgi edinme hakkı şeffaf yönetimi ve hesap verebilirliği güçlendirir."},
 {"unite":U7["U6"],"konu":"Toplumsal Katılım","yil":2023,"zorluk":"Zor","soru":"E-katılım;\nI. Online dilekçe\nII. E-devlet üzerinden şikâyet\nIII. Dijital oy kullanma\n\nE-katılımın demokrasiye katkısı hangisidir?","siklar":{"A":"Demokrasiyi zayıflatması","B":"Vatandaş katılımını kolaylaştırarak demokrasiyi güçlendirmesi","C":"Sadece gençlerin katılmasını sağlaması","D":"Hükümetin işini zorlaştırması"},"dogru_cevap":"B","aciklama":"E-katılım vatandaş katılımını kolaylaştırarak demokrasiyi güçlendirir."},
 {"unite":U7["U7"],"konu":"Küresel Sorunlar","yil":2024,"zorluk":"Orta","soru":"Plastik kirliliği;\nI. Okyanusları tehdit ediyor\nII. Deniz canlılarını öldürüyor\nIII. Parçalanması yüz yıllar alıyor\n\nPlastik kirliliğine karşı en etkili yaklaşım hangisidir?","siklar":{"A":"Plastik üretimini tamamen durdurmak","B":"Tek kullanımlık plastikleri azaltmak, geri dönüşümü artırmak ve biyobozunur alternatifler kullanmak","C":"Plastikleri okyanuslara atmak","D":"Sadece geri dönüşüm yapmak"},"dogru_cevap":"B","aciklama":"Azaltma, geri dönüşüm ve biyobozunur alternatifler birlikte en etkili yaklaşımdır."},
 {"unite":U7["U7"],"konu":"Uluslararası Örgütler","yil":2023,"zorluk":"Zor","soru":"Uluslararası Kızılhaç Komitesi (ICRC);\nI. Savaş bölgelerinde insani yardım sağlar\nII. Savaş hukuku (Cenevre Sözleşmeleri) uygulanmasını denetler\nIII. Savaş esirlerini korur\n\nICRC'nin en temel ilkesi hangisidir?","siklar":{"A":"Bir tarafı desteklemek","B":"Askeri güç kullanmak","C":"Tarafsızlık ve insanlık","D":"Ekonomik çıkar gözetmek"},"dogru_cevap":"C","aciklama":"ICRC'nin temel ilkesi tarafsızlık ve insanlıktır."},
 {"unite":U7["U1"],"konu":"Kitle İletişim","yil":2022,"zorluk":"Orta","soru":"Podcast yayıncılığı;\nI. Herkes içerik üretebilir\nII. Niş konularda uzmanlaşma mümkündür\nIII. Geleneksel medyaya alternatif oluşturur\n\nPodcast'ın iletişime katkısı hangisidir?","siklar":{"A":"Bilgi kirliliğini artırması","B":"İçerik üretimini demokratikleştirmesi","C":"Geleneksel medyayı yok etmesi","D":"Sadece müzik için kullanılması"},"dogru_cevap":"B","aciklama":"Podcast içerik üretimini demokratikleştirerek herkese yayın yapma imkânı sunar."},
 {"unite":U7["U2"],"konu":"Değişen Osmanlı","yil":2024,"zorluk":"Orta","soru":"Osmanlı'da Sanayi-i Nefise Mektebi (1882);\nI. Resim, heykel ve mimarlık eğitimi vermiştir\nII. Güzel sanatlar alanında ilk kurumsal eğitimdir\n\nBu mektebin önemi hangisidir?","siklar":{"A":"Askeri güçlendirme","B":"Sanat eğitimini kurumsal hale getirmesi","C":"Dini eğitim vermesi","D":"Tıp eğitimi sağlaması"},"dogru_cevap":"B","aciklama":"Sanayi-i Nefise sanat eğitimini kurumsal hale getiren ilk kurumdur."},
 {"unite":U7["U3"],"konu":"Nüfus","yil":2022,"zorluk":"Zor","soru":"Kentsel dönüşüm;\nI. Çarpık yapılaşma düzeltilir\nII. Depreme dayanıklı yapılar inşa edilir\nIII. Yaşam alanları modernleştirilir\n\nKentsel dönüşümün amacı hangisidir?","siklar":{"A":"Binaları yıkmak","B":"Sadece yeni binalar yapmak","C":"Güvenli, modern ve sürdürülebilir yaşam alanları oluşturmak","D":"Nüfusu azaltmak"},"dogru_cevap":"C","aciklama":"Kentsel dönüşüm güvenli, modern ve sürdürülebilir yaşam alanları oluşturmayı amaçlar."},
 {"unite":U7["U4"],"konu":"Avrupa'daki Değişimler","yil":2022,"zorluk":"Orta","soru":"Ansiklopedi hareketi (18. yy);\nI. Diderot ve d'Alembert öncülüğünde\nII. Tüm bilgiyi bir eserde toplamayı amaçlamış\nIII. Aydınlanma düşüncesinin yayılmasına katkıda bulunmuş\n\nAnsiklopedinin en önemli katkısı hangisidir?","siklar":{"A":"Bilginin tekelleşmesi","B":"Bilginin halka ulaşması ve eleştirel düşüncenin yayılması","C":"Kilisenin güçlenmesi","D":"Monarşinin desteklenmesi"},"dogru_cevap":"B","aciklama":"Ansiklopedi bilginin halka ulaşmasını ve eleştirel düşüncenin yayılmasını sağlamıştır."},
 {"unite":U7["U5"],"konu":"Toprak ve İklim","yil":2022,"zorluk":"Orta","soru":"Türkiye'de madencilik;\nI. Krom, bor, mermer zengin\nII. Zonguldak'ta taşkömürü\nIII. Batı Anadolu'da jeotermal\n\nMaden kaynaklarının ekonomiye katkısı hangisidir?","siklar":{"A":"Sadece ihracat geliri","B":"Ham madde sağlayarak sanayiyi desteklemesi ve ihracat geliri kazandırması","C":"Çevreyi kirletmesi","D":"İşsizliği artırması"},"dogru_cevap":"B","aciklama":"Maden kaynakları sanayiye ham madde sağlar ve ihracat geliri kazandırır."},
 {"unite":U7["U6"],"konu":"Haklar","yil":2022,"zorluk":"Zor","soru":"Osmanlı'dan Cumhuriyet'e yönetim biçimi değişimi;\nSaltanat → Meşrutiyet → Cumhuriyet\n\nBu değişim sürecinin yönü hangisidir?","siklar":{"A":"Monarşiye dönüş","B":"Otoriter yönetime geçiş","C":"Millet egemenliğine doğru ilerleyen demokratikleşme","D":"Teokrasiye geçiş"},"dogru_cevap":"C","aciklama":"Saltanattan Cumhuriyet'e millet egemenliğine doğru demokratikleşme süreci yaşanmıştır."},
 {"unite":U7["U7"],"konu":"Küresel Sorunlar","yil":2022,"zorluk":"Orta","soru":"Dünyada her yıl yaklaşık 1.3 milyar ton gıda israf edilmektedir.\n\nGıda israfını azaltmanın yolu hangisidir?","siklar":{"A":"Daha çok üretmek","B":"Farkındalık kampanyaları, planlı alışveriş ve gıda bankacılığı uygulamak","C":"Yemek yemeyi azaltmak","D":"Sadece organik gıda tüketmek"},"dogru_cevap":"B","aciklama":"Farkındalık, planlı alışveriş ve gıda bankacılığı israfı azaltmanın etkili yollarıdır."},
 {"unite":U7["U1"],"konu":"İletişim","yil":2021,"zorluk":"Orta","soru":"Asertif (kendini doğru ifade edebilen) kişi;\nI. Haklarını savunur ama başkalarını incitmez\nII. Hayır demeyi bilir\nIII. Hem kendi hem karşıdakinin haklarına saygı gösterir\n\nAsertif iletişimin yararı hangisidir?","siklar":{"A":"Sürekli kavga etmek","B":"Sağlıklı ilişkiler kurmak ve özgüvenli olmak","C":"Herkese boyun eğmek","D":"Her zaman haklı olmak"},"dogru_cevap":"B","aciklama":"Asertif iletişim sağlıklı ilişkiler ve özgüven sağlar."},
 {"unite":U7["U4"],"konu":"Osmanlı'da Bilim","yil":2021,"zorluk":"Zor","soru":"Osmanlı'da Darülfünun (1900);\nI. Osmanlı'nın ilk üniversitesidir\nII. Fen, edebiyat, hukuk bölümleri vardı\nIII. Cumhuriyet döneminde İstanbul Üniversitesi'ne dönüşmüştür\n\nDarülfünun'un önemi hangisidir?","siklar":{"A":"Osmanlı'da yüksek öğretimin kurumsal başlangıcı","B":"Sadece dini eğitim vermesi","C":"Kadınlara eğitim yasaklaması","D":"Batı'dan farklı olması"},"dogru_cevap":"A","aciklama":"Darülfünun Osmanlı'da yüksek öğretimin kurumsal başlangıcıdır."},
 {"unite":U7["U3"],"konu":"İklim","yil":2021,"zorluk":"Orta","soru":"Afet hazırlığı;\nI. Deprem çantası hazırlamak\nII. Toplanma alanlarını bilmek\nIII. Tatbikata katılmak\n\nAfet hazırlığının önemi hangisidir?","siklar":{"A":"Sadece devletin sorumluluğu olması","B":"Can ve mal kayıplarını en aza indirmek","C":"Afetleri önlemek","D":"Korku yaratmak"},"dogru_cevap":"B","aciklama":"Afet hazırlığı can ve mal kayıplarını en aza indirmeyi amaçlar."},
]

# 8. SINIF EK (59 soru) - LGS bazlı
U8 = {"U1":"Ünite 1 – Bir Kahraman Doğuyor","U2":"Ünite 2 – Millî Uyanış: Bağımsızlık Yolunda Atılan Adımlar","U3":"Ünite 3 – Millî Bir Destan: Ya İstiklal Ya Ölüm!","U4":"Ünite 4 – Atatürk ve Çağdaşlaşan Türkiye","U5":"Ünite 5 – Demokratikleşme Çabaları","U6":"Ünite 6 – Atatürk Dönemi Türk Dış Politikası"}
ek8 = [
 {"unite":U8["U1"],"konu":"I. Dünya Savaşı","yil":2024,"zorluk":"Orta","soru":"Osmanlı'nın I. Dünya Savaşı'na girmesiyle Rusya'ya karşı Kafkas Cephesi açılmıştır.\n\nKafkas Cephesi'nin açılmasının stratejik amacı hangisidir?","siklar":{"A":"Rusya ile ticaret yapmak","B":"Türk dünyasıyla bağlantı kurmak ve Rusya'yı zayıflatmak","C":"Balkanları geri almak","D":"Mısır'ı fethetmek"},"dogru_cevap":"B","aciklama":"Kafkas Cephesi Türk dünyasıyla bağlantı ve Rusya'yı zayıflatma amaçlıydı."},
 {"unite":U8["U1"],"konu":"Osmanlı'nın Son Dönemi","yil":2023,"zorluk":"Zor","soru":"Balkan Savaşları'nın Osmanlı üzerindeki etkileri;\nI. Batı Trakya ve Makedonya kaybedilmiş\nII. Milyonlarca Müslüman göçmen gelmiş\nIII. Orduda reform ihtiyacı artmış\nIV. Türkçülük fikri güçlenmiş\n\nDoğru olanlar hangileridir?","siklar":{"A":"I ve II","B":"I, II ve III","C":"I, II, III ve IV","D":"Yalnız I"},"dogru_cevap":"C","aciklama":"Tüm maddeler Balkan Savaşlarının sonuçlarıdır."},
 {"unite":U8["U1"],"konu":"Mustafa Kemal","yil":2024,"zorluk":"Orta","soru":"Mustafa Kemal'in Harp Akademisi'nde 'Vatan Tehlikededir' konulu makale yazması neyi gösterir?","siklar":{"A":"Sadece iyi bir öğrenci olduğunu","B":"Genç yaşta vatansever ve siyasi bilinçli bir kişiliğe sahip olduğunu","C":"Gazetecilik yapmak istediğini","D":"Savaştan korktuğunu"},"dogru_cevap":"B","aciklama":"Genç yaşta vatan konulu makale vatansever ve siyasi bilinçli kişiliğini gösterir."},
 {"unite":U8["U2"],"konu":"İşgaller","yil":2024,"zorluk":"Zor","soru":"Yunan ordusunun Batı Anadolu'da sivil halka zulmetmesi;\nI. Uluslararası kamuoyunda tepki yaratmış\nII. Türk halkının direniş kararlılığını güçlendirmiş\nIII. Kuvâ-yı Milliye hareketini hızlandırmış\n\nDoğru olanlar hangileridir?","siklar":{"A":"Yalnız II","B":"I ve II","C":"I, II ve III","D":"Yalnız I"},"dogru_cevap":"C","aciklama":"Zulüm tepki, kararlılık ve Kuvâ-yı Milliye hızlanmasına neden olmuştur."},
 {"unite":U8["U2"],"konu":"Kongreler","yil":2024,"zorluk":"Orta","soru":"Balıkesir ve Alaşehir Kongrelerinde Batı Anadolu'daki direniş organize edilmiştir.\n\nBu kongrelerin karakteri hangisidir?","siklar":{"A":"Ulusal nitelikte","B":"Bölgesel nitelikte","C":"Uluslararası nitelikte","D":"Askeri nitelikte"},"dogru_cevap":"B","aciklama":"Balıkesir ve Alaşehir bölgesel direniş kongreleridir."},
 {"unite":U8["U2"],"konu":"TBMM","yil":2023,"zorluk":"Zor","soru":"TBMM'nin açılışında Mustafa Kemal'in meclis başkanı seçilmesi;\nI. Liderliğinin tanınması\nII. Millî Mücadele'nin tek merkezden yönetilmesi\nIII. Padişah yetkilerinin TBMM'ye geçmesi\n\nBu gelişmenin önemi hangisidir?","siklar":{"A":"Yalnız I","B":"I ve II","C":"I, II ve III","D":"Yalnız III"},"dogru_cevap":"C","aciklama":"Meclis başkanlığı liderlik tanınması, merkezi yönetim ve yetki devri anlamına gelir."},
 {"unite":U8["U3"],"konu":"Batı Cephesi","yil":2024,"zorluk":"Orta","soru":"Büyük Taarruz öncesi Mustafa Kemal'in gizli hazırlığı;\nI. Futbol maçı organize edip düşmanı yanıltmış\nII. Askeri harekâtı gizli tutmuş\nIII. Sürpriz taarruz planlamış\n\nBu hazırlık hangisini gösterir?","siklar":{"A":"Savaştan kaçınmak istediğini","B":"Üstün askeri strateji ve aldatma yeteneğini","C":"Futbola meraklı olduğunu","D":"Barış istediğini"},"dogru_cevap":"B","aciklama":"Gizli hazırlık ve aldatma üstün askeri stratejiyi gösterir."},
 {"unite":U8["U3"],"konu":"Güney Cephesi","yil":2023,"zorluk":"Orta","soru":"Adana (Çukurova) bölgesinde halk Fransız-Ermeni işgaline karşı diremiştir.\n\n20 Ekim 1921 Ankara Antlaşması'yla Fransa Güney'den çekilmiştir. Bu durum hangisini kanıtlar?","siklar":{"A":"Fransızların güçlü olduğunu","B":"Halkın silahlı direnişinin diplomatik başarıya dönüştüğünü","C":"İşgalin devam ettiğini","D":"TBMM'nin zayıf olduğunu"},"dogru_cevap":"B","aciklama":"Halkın direnişi diplomatik başarıyla (Ankara Antlaşması) sonuçlanmıştır."},
 {"unite":U8["U3"],"konu":"Lozan","yil":2024,"zorluk":"Zor","soru":"Lozan'da Türk heyetinin en çok zorlandığı konular;\nI. Kapitülasyonlar\nII. Osmanlı borçları\nIII. Boğazlar rejimi\n\nLozan'ın başarısı hangisidir?","siklar":{"A":"Tüm sorunların çözüldüğü","B":"Tam bağımsızlık ve egemenliğin uluslararası güvence altına alınması","C":"Toprak kazanılması","D":"Borçların silinmesi"},"dogru_cevap":"B","aciklama":"Lozan'ın en büyük başarısı tam bağımsızlık ve egemenliğin güvence altına alınmasıdır."},
 {"unite":U8["U4"],"konu":"İnkılaplar","yil":2024,"zorluk":"Orta","soru":"Tekke, zaviye ve türbelerin kapatılması (1925);\n\nBu kararın amacı hangisidir?","siklar":{"A":"İslam'ı yasaklamak","B":"Laikliği güçlendirmek ve dini kurumların siyasi etkisini ortadan kaldırmak","C":"Kültürel mirası yıkmak","D":"Halkı cezalandırmak"},"dogru_cevap":"B","aciklama":"Bu karar laikliği güçlendirmeyi ve dini kurumların siyasi etkisini kaldırmayı amaçlamıştır."},
 {"unite":U8["U4"],"konu":"Atatürk İlkeleri","yil":2023,"zorluk":"Zor","soru":"Atatürk'ün 'Muhtaç olduğun kudret damarlarındaki asil kanda mevcuttur' sözü;\n\nBu söz hangisini ifade eder?","siklar":{"A":"Savaşçılığı","B":"Milletin kendi gücüne olan inancını ve bağımsızlık ruhunu","C":"Kan bağını","D":"Dış yardım gerekliliğini"},"dogru_cevap":"B","aciklama":"Bu söz milletin kendi gücüne inanmasını ve bağımsızlık ruhunu ifade eder."},
 {"unite":U8["U5"],"konu":"Demokratikleşme","yil":2024,"zorluk":"Orta","soru":"Türkiye'de basın tarihi;\nI. Takvim-i Vekâyi (1831) - İlk resmi gazete\nII. Tercüman-ı Ahvâl (1860) - İlk özel gazete\nIII. Cumhuriyet dönemi - Basın özgürlüğü genişlemiş\n\nBasının toplumsal rolü hangisidir?","siklar":{"A":"Eğlence sağlamak","B":"Kamuoyunu bilgilendirmek ve yönetimi denetlemek","C":"Devleti güçlendirmek","D":"Reklam yapmak"},"dogru_cevap":"B","aciklama":"Basın kamuoyunu bilgilendirir ve yönetimi denetler."},
 {"unite":U8["U6"],"konu":"Dış Politika","yil":2024,"zorluk":"Orta","soru":"Atatürk'ün dış politikada 'akılcılık ve gerçekçilik' ilkesi;\n\nBu ilke hangi yaklaşımı ifade eder?","siklar":{"A":"Duygusal kararlar almayı","B":"Mevcut koşulları doğru değerlendirerek uygulanabilir politikalar üretmeyi","C":"Her zaman savaşmayı","D":"Dış politikayı görmezden gelmeyi"},"dogru_cevap":"B","aciklama":"Akılcılık ve gerçekçilik mevcut koşulları doğru değerlendirmeyi gerektirir."},
]

print("="*60)
print("EKSİK SORULARI TAMAMLAMA VE DAĞILIMı DENGELEME")
print("="*60)

add_and_balance(6, ek6)
add_and_balance(7, ek7)
add_and_balance(8, ek8)

print("\nTamamlandı! Şimdi birlestir.py çalıştırılmalı.")
